### ISSUE TITLE
feature request: custom ports for monorepo with multiple expo projects

### ISSUE THREAD

**Issue by alidcastano** [expo/expo-cli#1045]
## Description

allow custom ports so that multiple expo projects can run at once. this is useful for example if you have an expo `mobile` project as one package and an expo `web` project in another

## Expected Behavior

I tried `packagerOpts.port` option mentioned in https://github.com/expo/expo/issues/178 and `manifestPort` mentioned in older repo https://github.com/react-community/create-react-native-app/issues/108

## Observed Behavior

Port did not change so projects could not run at the same time.

## Environment

```
 Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.3 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.1.2`
```

**Comment by alidcastano** [comment]
also curious do you guys intend for separate expo projects to run in conjunction or is it intended only to be used as a single application package?

example use-case: 
```
\ packages 
    \ mobile # expo instance for mobile app 
    \ web # expo instance for web app 
    \ shared # expo instance running storybook for shared components 
```

**Comment by ccheever** [comment]
Hi--

It should work to run multiple expo projects at once. By default, `expo-cli` will look for available ports and run on those rather than just always using the same port.

I just verified that this still works by running two different examples from the http://github.com/expo/examples at the same time on the same computer.

The ports chosen will typically be in the 19000 range.

I verified that the metro bundler packager port option that you referenced does still work, but note that there are multiple servers that Expo needs to run when you're starting a project, like Expo DevTools etc. Ex. Here I set the packagerPort to 6969 and it works but other servers also get spun up.
```

Starting project at /Users/ccheever/tmp/examples/with-formdata-image-upload/app
Expo DevTools is running at http://localhost:19003
Opening DevTools in the browser... (press shift-d to disable)
Starting Metro Bundler on port 6969.
Tunnel ready.

  exp://192.168.1.28:19004

```


In terms of mobile/web/shared, we are still learning as we work through web being in beta, but in general, our goal is to make it so you have just one app that runs the as-close-to-the-same as possible on all the different platforms.

So, it would be something like:
```
    your-app/
        App.js
        someComponentThatsDiffOnDiffPlatforms.ios.js
        someComponentThatsDiffOnDiffPlatforms.android.js
        someComponentThatsDiffOnDiffPlatforms.web.js
        sharedComponent.js
        package.json
        app.json
          
```
 
Does this make sense?
