### ISSUE TITLE
expo-cli installation issue 

### ISSUE THREAD

**Issue by paribaranwal** [expo/expo-cli#1055]
Getting this issue while installing expo-cli, few months back i was able to install with same OS level permissions.
\Roaming\npm\node_modules\expo-cli\node_modules\@expo\.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll
npm ERR! code EPERM
npm ERR! errno -4048

**Comment by forresst** [comment]
I had the same error on Windows. To fix this problem, I removed expo-cli on my PC:

`npm uninstall -g expo-cli`

I then deleted the directory `expo-cli` and its subdirectories (`\Roaming\npm\node_modules\expo-cli`). I had to do this because the removal of expo-cli went wrong because of rights issues on this directory.

Finally I reinstalled `expo-cli`:
`npm install -g expo-cli`

I don't have any more mistakes now.

**Comment by paribaranwal** [comment]
It solved form me by giving every permission to expo-cli module directory in global node_modules.

**Comment by ccheever** [comment]
Hi--

From  my research, this seems to be a common problem with installing `npm` packages in general, and not something specific to expo-cli.

It seems like the root of the problem that triggers errno -4048 is apparently when files/directories get locked by other processes and can't be written to. 

Restarting your computer may be one way to solve this problem.

Beyond that, there are some other ideas here for solving it: https://stackoverflow.com/questions/30860795/fail-to-install-npm-package-npm-err-errno-4048

There are a number of different things that could cause this so any specific solution may or may not work for you.

Closing this for now but reopen if you encounter this and none of the solutions in the SO question linked to and restarting your computer don't work.
