### ISSUE TITLE
Can I edit native classes (.java/.kt and .swift/.m/.h) on the expo's turtle-cli service on my own server?

### ISSUE THREAD

**Issue by AlexandreLage** [expo/expo-cli#1140]
Hello expo experts,

I have been wondering if I should use Expo and therefore its online building tool (turtle-cli, on my own server) for my team's projects.

If we decide to use Expo, I would not like to eject to a normal standalone react-native app project whenever I need to edit native-language-written classes.

I want to maintain the Expo SDK instead. I want to be able to edit Java and Objective C classes whenever I need and still use the powerful expo-cli for building (locally and online -- with turtle-cli).

The question is: is it possible to edit these environment-native classes (java and objective c) files and still use expo-cli and turtle-cli api for building our apps?

If so, how could I do it? I know I can edit node_modules/expo files... but I wonder if there is some standardized way of keeping track of versioning of these edits for instance.

I understand it would be better not to have the expo sdk folder inside node_modules folder in this case.

Has anybody worked with Expo in these terms before?

I have checked turtle-cli repository (github) but I didn't find .java classes :'(

Thank you a lot. This question's been bothering me.

https://stackoverflow.com/questions/58489340/can-i-edit-native-classes-java-kt-and-swift-m-h-on-the-expos-turtle-cli

**Comment by esamelson** [comment]
Hey @AlexandreLage - unfortunately no, this is not easily possible with turtle-cli. Both turtle-cli and the `expo build` service we provide (which basically just runs turtle-cli on our server) take prebuilt "shell" iOS and Android apps and mostly just make modifications to static files to customize them into your app. In order to modify the native code you'd need to rebuild these "shell" apps that turtle-cli uses. We don't provide documentation around it -- you'd need to check out the [expo repo](https://github.com/expo/expo) and figure it out yourself.

All of which is to say, while this is possible in theory, you'd most likely be better off using the [bare workflow](https://docs.expo.io/versions/v35.0.0/bare/exploring-bare-workflow/), where you have complete control over your native projects and can customize them as little or as much as you need.

Hope that makes sense! In the future, please ask questions like this on our [forums](https://docs.expo.io/versions/v35.0.0/bare/exploring-bare-workflow/) instead -- GitHub issues are for bug reports with current versions of our software. That will help us get to your (and others') questions in a more timely manner! 🙂
