### ISSUE TITLE
Remove and change the Expo web page's meta description content="A Neat Expo App"

### ISSUE THREAD

**Issue by 5ervant** [expo/expo-cli#1171]
Upon trying to change my web page description using `react-helmet` in Expo Web with the following code, I'm also seeing `<meta name="description" content="A Neat Expo App">` with my inserted description on my web page's HTML elements:

    import { Helmet } from 'react-helmet';
    ...
        <Helmet>
          <title>My Title</title>
          <meta name="description" content="My description" />
        </Helmet>

Any solution how to get rid of that default meta description?
Or a standard way to change the web page title and description with Expo Web?

**Comment by jonathonlui** [comment]
The `webpack-pwa-manifest-plugin` inserts the meta description tag with the `description` value from `app.json` manifest:

https://github.com/expo/expo-cli/blob/5e8ed82601a965e6d41e86f73817d2f3302073f2/packages/webpack-pwa-manifest-plugin/src/createMetatagsFromConfig.ts#L53-L60

And it'll use the hardcoded value you're seeing if the `app.json` value is falsy (which it is in a default expo project): https://github.com/expo/expo-cli/blob/64a54cf2db50433f5459939c8e9fba0e0f171280/packages/config/src/Config.ts#L218

So although you can't remove the meta description tag, you can override the text to whatever static string you want by changing your project's `app.json`.

The web page title is also pulled from `app.json`. This is done by `ExpoHtmlWebpackPlugin`. You can define a web-specific value  using `web.name` otherwise it'll default to `name`. https://github.com/expo/expo-cli/blob/64a54cf2db50433f5459939c8e9fba0e0f171280/packages/config/src/Config.ts#L162-L163

**Comment by 5ervant** [comment]
@jonathonlui The problem is we want to have a unique description every page.

**Comment by jonathonlui** [comment]
Expo web builds are, by default, singe-place apps and `react-helmet` does dynamically update the DOM as different `<Helmet>` components are mounted.

But it sounds like you want each page to be pre-rendered as a static pages with different header tags so you'll need investigate server-side rendering. Although I've not tried it Expo has [built-in support for next.js](https://docs.expo.io/versions/v35.0.0/guides/using-nextjs/).

**Comment by 5ervant** [comment]
No @jonathonlui, I'm just building multiple `react-navigation` screens, each with different:

    <Helmet>
      <title>{title}</title>
      <meta name="description" content={description} />
    </Helmet>

**Comment by fitd-tech** [comment]
When I searched for the ability to add custom meta tags, I found this issue. I think a link to this guide may help others looking for the same thing: [Static Rendering](https://docs.expo.dev/router/reference/static-rendering/)
