### ISSUE TITLE
Build reuse warning potentially confusing and not always accurate

### ISSUE THREAD

**Issue by ExpoNfinity** [expo/expo-cli#1251]
After latest expo cli update it started to suck in the middle of apk build process with the following message:

Checking if there is a build in progress...

Publishing to channel 'default'...
Building iOS bundle
Building Android bundle
Analyzing assets
Uploading assets
No assets changed, skipped.
Processing asset bundle patterns:
- c:\Work\gdynia-app-react\**\*
Uploading JavaScript bundles
Published
Your URL is

https://exp.host/@.../...

Checking if this build already exists...

Did you know that Expo provides over-the-air updates?
Please see the docs (https://docs.expo.io/versions/latest/guides/configuring-ota-updates/) and check if you can use them instead of building your app binaries again.
There were no new changes from the last build, you can download that build from here: https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40.../...-99c232aacb9443caa23820374a82e8e0-signed.apk
? Do you want to build app anyway? (Y/n)

To continue i have to press Y, to notice the need of this i have to waste time watching debug console. Also this message comes always, for sure there are differences. 

Please fix this bug.

**Comment by jonathanstiansen** [comment]
We're seeing this too, we are certainly changing code as well - so whatever hash you're using to compare doesn't seem to be working.

**Comment by brentvatne** [comment]
if there is a build that already exists for the project with the current user for the given slug on the given release channel, for the given sdk version and platform, you see this warning. this is because you can update the project by doing an over the air update with `expo publish`. it is not necessary to rebuild the binary on each update.

sources:
- https://github.com/expo/expo-cli/blob/0a9f29dba1e37ddaf50291a4c7dcd9fa7f6ceab6/packages/xdl/src/Project.ts#L683-L699
- https://github.com/expo/expo-cli/blob/9f8ceaf9ccb6b4b726a0103616c0629f1a37d419/packages/expo-cli/src/commands/build/BaseBuilder.js#L146-L181

that said, there are some reasons why you might want to re-build the binary even when these properties are all identical. for example, maybe you want to update the bundled assets or bundled js, or you want to add some native config in app.json.

i think this warning is not comprehensive enough and we should update it.

<hr />

one point i need clarity on:

> To continue i have to press Y, to notice the need of this i have to waste time watching debug console. Also this message comes always, for sure there are differences.

what do you mean by "waste time watching the debug console" here?

**Comment by brentvatne** [comment]
related: this warning caused https://github.com/expo/expo-cli/issues/1224

**Comment by ExpoNfinity** [comment]
Thank you for clarification. 
> mean by "waste time watching the debug console" here?
- to answer 'Y' when the message will appear, otherwise whole process will stuck. I now see that with OTA i should not want to build new apk. 

But there's another problem that may worth another issue - seems like even latest apk does not have latest codebase inside, as people often report that latest apk after clean install does not look as expected, but on second run it changes itself

**Comment by brentvatne** [comment]
yeah i think these are good enough reasons to make this a non-blocking warning for now, thanks for getting back to me

**Comment by ExpoNfinity** [comment]
Please review possibility and need to show by default some OTA update sign, it will catch more attention to OTA of those who moved from previous sdks and could think that it just didn't work without reading details

**Comment by alexsenichev** [comment]
Same for me. We have a pipeline and can't pass it manually
