### ISSUE TITLE
[webpack-config] expo-service-worker is always registered in the root

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo-cli#1330]
Tracking the [reported bug here](https://github.com/expo/web-examples/issues/40#issuecomment-563420589). It appears that the service worker only works when the site is deployed relative to the root. This breaks deployment to GH pages.

- [ ] Ensure the `withWorkbox` addon is observing the `homepage` field when registering a service worker.

**Comment by yingshaoxo** [comment]
In case someone confused about all of those things. I'd like to add a comment here.

___

You can add a property to `package.json` to solve this problem:
```
  "homepage": "/ui/",
```

Now after `expo build:web`, you would be able to visit your app by `http://127.0.0.1/ui/` instead of `http://127.0.0.1`

**Comment by AlexGrafe** [comment]
Thanks for tracking on this repo. But can this please be fixed?
I am using a monorepo that creates multiple apps from the same code source but has different app.json files per singular app. Thus I can have those different app.json files say `web.publicPath: /app1`, `web.publicPath: /app2`, `web.publicPath: /app3`, but it's not great to have to change the package.json.

Especially since `web.publicPath` already worked well in the past.

**Comment by rickysullivan** [comment]
> You can add a property to `package.json` to solve this problem:
> 
> ```
>   "homepage": "/ui/",
> ```

This needs to be documented. I was pulling my hair out trying to hack a custom webpack config to fix this.

**Comment by brentvatne** [comment]
@rickysullivan - can you open a PR to document this wherever you would have expected to find it?

**Comment by kopax** [comment]
I have issue with expo SDK36, I can't get the expo-service-worker to load on port `4001` (express), it keep trying to load on port `:19006` and that's causing many troubles. Is there a way to fix this?
