### ISSUE TITLE
Where can I find my build ids?

### ISSUE THREAD

**Issue by mi-mazouz** [expo/expo-cli#1383]
Hi, I have few questions where I can't find answers in the documentation.

In the doc I can see --id option for the 'expo upload:android/ios' command but I can't find any build ids. Is it the channelId or publishId? Where I can find them?

I wanted to know if there is a way to upload my apk to a specific group on testflight or a specific channel like alpha or beta for android instead to do it manually.

Thanks for your help!!

**Comment by brentvatne** [comment]
hello!

> In the doc I can see --id option for the 'expo upload:android/ios' command but I can't find any build ids. Is it the channelId or publishId? Where I can find them?

when you do a build it will give you the build id as soon as the build starts. another way to get the id is to go to https://expo.io/dashboard/ then click on the build then copy it from the url - it's the last part of the url. we should probably add this to the build page itself!

that said, you don't need to actually provide an id when running the upload command. if you leave out the `--id` flag, the command will just use the latest binary build for the respective platform.

> I wanted to know if there is a way to upload my apk to a specific group on testflight or a specific channel like alpha or beta for android instead to do it manually.

the options available for the `expo upload:ios` and `expo upload:android` commands are documented with the `--help` flag (as i think you noticed already given the first question :smile:).  there is no such option for ios, but once it's uploaded using the command `expo upload:ios` it is easy to release it in testflight beta through the apple developer web interface. `expo upload:android` provides a `--track` option that you can use eg: `--track alpha`.

hope that helps! in the future, https://forums.expo.io is a better place for these types of questions. we generally use issues for bug reports rather than questions.

**Comment by mi-mazouz** [comment]
@brentvatne thanks for answering. Yeah I think you should add the build id in the build details page

**Comment by YajJackson** [comment]
Adding the build ids to build:status as well.

**Comment by brentvatne** [comment]
@YajJackson - pr welcome! it's on the build details page now btw

**Comment by syyykes** [comment]
This is less than ideal, but since there's still no way to retrieve the build id for a build on a specific release channel, this is how I'm getting the build id and passing it to `expo upload:ios`. The build id is in the output of `expo build:ios`, so you can just parse that output...
```
npx expo build:ios --release-channel dev | tee buildout.txt
buildid=$(cat buildout.txt | grep expo.io/dashboard/.*/builds | cut -d'/' -f 7)
npx expo upload:ios --id $buildid
```
