### ISSUE TITLE
Unable to resolve "react-navigation-drawer" on the blank app

### ISSUE THREAD

**Issue by Latgals** [expo/expo-cli#1387]
## Description

After all the updates: Expo SDK, expo-cli I installed a blank application using `expo init` using the `tabs` template. 
First, the splash screen starts to open, and then an error is issued:

```
Unable to resolve "react-navigation-drawer" from "node_modules\react-navigation\src\react-navigation.js"
Failed building JavaScript bundle.
```

## Environment

Expo CLI 3.11.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.13.4 - C:\Users\Owner\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548

- Phone/emulator/simulator platform, model and version:

Phone LG K9 Model LMX210NMW, 
OS Android 7.1.2
Expo client version: 2.14.0

**Comment by brentvatne** [comment]
i think you might have another packager running or something, because the tabs project does not include react-navigation-drawer.

i just initialized a new project from the tabs template to verify this and could not repro or find any import of react-navigation-drawer. please create a new issue with a reproducible example if the problem persists, thanks!
