### ISSUE TITLE
Build Webhook not fired 

### ISSUE THREAD

**Issue by AlbertoLopSie** [expo/expo-cli#1414]
## Description
Expo webhooks not firing

## Expected Behavior

I set a webhook to fire upon finishing build according to https://docs.expo.io/versions/latest/distribution/building-standalone-apps/#4-wait-for-it-to-finish-building but it never fires

## Observed Behavior

Nothing. No HTTP POST is made (nor message in build console) 

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```

```

## Environment

albertos-imac:test-ci alberto$ expo diagnostics

  Expo CLI 3.11.3 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ~4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.3

Also specify:

- iPhone X simulator 12.0 (not run ever. Just trying to make the build producing a finished event)

## Reproducible Demo

On an Expo minimal project, set:
```
$ expo webhooks:set --event build --url "https://gitlab.com:443/api/v4/projects/16195403/trigger/pipeline?token=35af4dc0215623cc5eabd45ed20ff7&ref=master"

$ expo webhooks:show
Fetching webhooks for @digicard/test-ci

Webhook type: build
Webhook URL: https://gitlab.com:443/api/v4/projects/16195403/trigger/pipeline?token=35af4dc0215623cc5eabd45ed20ff7&ref=master
Webhook secret: xxxxxxxxxxxxx

$ expo build:ios --no-wait [--no-publish]
```
It uses a GitLab Public project at https://gitlab.com/AlbertoLopSie/test-ci-hooks

The pipeline gets fired if invoked through:
```
$ curl -X POST "https://gitlab.com/api/v4/projects/16195403/trigger/pipeline?token=35af4dc0215623cc5eabd45ed20ff7&ref=master"
```

**Comment by cjke** [comment]
I can confirm this is happening for us too, but only since the 7th Jan. Previous to that we had almost daily builds triggering hooks that have suddenly stopped working - nothing in our codebase has changed related to the handling of webhooks. 

I can't add much outside of this is the line we use (and continue to use):

```
expo webhooks:set --event build --url https://[our-endpoint-host]/webhook/expo/ios
```

**Comment by gCardinal** [comment]
Can't add much either, but I can add that it's also the case for us; webhooks are not being sent.

**Comment by cjke** [comment]
Hi @quinlanj can we at least confirm this is on Expo's radar? 

If there is no intent to fix at the Expo end, then our team needs to know so we can implement a work around somehow (currently we're just manually triggering our webhooks by monitoring the expo dashboard). We're content doing this manually in the interim but the hours add up, so if fixing isn't on the radar we need to factor in some dev time to fix it on our end (with a workaround)

**Comment by seanmullins** [comment]
Hi, same with us - recently stopped working.
Can we get an update on this please?
Cheers.

**Comment by cjke** [comment]
I really don't like paging maintainers but this still seems to be broken with no visibility/input from the Expo team. @EvanBacon can we at least verify that this is on Expo's radar in some form?

**Comment by mskg** [comment]
This now also happens for me without any change to the workflow. I can confirm the behavior: No call to the webhook targets at all.

**Comment by cjke** [comment]
Indeed @mskg , its still happening for us and we've had to continue running our tasks manually. @brentvatne this seems like a pretty large bug - as above, I don't like @'ing people but it would be ace to know if Expo acknowledges this as an issue or not?

**Comment by mskg** [comment]
They are aware of the problem and working on it (now).

**Comment by jkhales** [comment]
Looking into this, thanks @mskg

**Comment by cjke** [comment]
Thanks @jkhales - any updates would be much appreciated. Our team is still manually deploying because of the missing hook, which makes our CI/CD not so continuous

**Comment by jkhales** [comment]
> Thanks @jkhales - any updates would be much appreciated. Our team is still manually deploying because of the missing hook, which makes our CI/CD not so continuous

Thats very frustrating. Let's get this solved.

I'm having difficulty repro'ing this issue on a fresh project and using https://webhook.site/. Namely its been working every time. 

Would you mind checking if setting a dummy webhook on your project with this site fails as well?

Also can you send your username and the project name to jonathan@expo.io so I can see if there is anything wrong with your webhook in the db?

**Comment by cjke** [comment]
Thanks jkhales. Next deployment is Monday where we will be also updating to latest Expo - so hopefully the overall combination works. I will let you know

**Comment by mymattcarroll** [comment]
I thought this was an issue for us as well, turned out that our webhook was being called with this header on the 20th of March 2020

`Expo-Signature`

And on the 31st of March 2020, was being called with this header

`expo-signature`

10 points to anyone that can spot the difference ;)

Unfortunately we dont have requests between those dates, so can't be more accurate on when the change occurred.

We made a change to our code today to look for `expo-signature`, so please don't change it back to `Expo-Signature`.

**Comment by jkhales** [comment]
> I thought this was an issue for us as well, turned out that our webhook was being called with this header on the 20th of March 2020
> 
> `Expo-Signature`
> 
> And on the 31st of March 2020, was being called with this header
> 
> `expo-signature`
> 
> 10 points to anyone that can spot the difference ;)
> 
> Unfortunately we dont have requests between those dates, so can't be more accurate on when the change occurred.
> 
> We made a change to our code today to look for `expo-signature`, so please don't change it back to `Expo-Signature`.

Thanks for this great analysis @mymattcarroll , I checked around and we indeed changed the header. We are going to keep it all lowercase.

**Comment by cobyfielding** [comment]
I stopped receiving webhooks a day or so ago.  I log the requests when they come in so I can verify receiving them, and I have not received one since 4/14.  Completed one build yesterday, and 2 today without webhooks being sent.  I did notice in the logs that the webhook request I received on 4/14 has `Expo-Signature` in the request, which seems to be inconsistent with what others have posted.  If I can provide any information that will help solve the problem, please let me know.  Also, if this is going to be a long term issue please let me know as well, as the webhook triggers the automatic upload for our apps.  I'd rather not change our process if this can be resolved quickly.  Thanks

**Comment by jkhales** [comment]
We've identified a potential fix and are working on a PR.

**Comment by jkhales** [comment]
Deployed a fix.

**Comment by cjke** [comment]
@jkhales Can you elaborate on what was fixed and if we should change anything our end?

**Comment by cjke** [comment]
After a lot of fiddling around I can see what changed for us. Previously, the webhook would return an artifactUrl that redirected **once**, like so:

1. 301 https://expo.io/artifacts/[uuid4]  (from response body)
2. 200 https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/[app-name]/[app-name]-[uuid4]-archive.ipa (actual download)

Sometime this year it has swapped to a artifactUrl that redirects **twice**, like so:

1. 301 https://expo.io/artifacts/[uuid4] (from response body)
2. 301 https://exp.host/--/artifacts/[uuid4]
3. 200 https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/[app-name]/[app-name]-[uuid4]-archive.ipa (actual download)

We needed to update our webhook handler to follow through two directs and fetch the actual download at the end. This was in addition to the expo-signature change. 

As @mymattcarroll said - "please don't change it back" . @jkhales These are pretty substantial changes on a production API at your end that causes significant time (and cost) to rectify. Is there any way we, as users of the service, can access to either a changelog or similar so we can avoid it in future? 

Additionally can you version your webhooks so we can subscribe to a "version 1" of the webhook feature set? 
Something along the lines of `expo webhooks:set --event build --version 1.0 --url example.org`

**Comment by jkhales** [comment]
That sounds frustrating, thanks for this great write up. I will ask around and investigate.

**Comment by cjke** [comment]
Just an update to the above. It is now `add` or `update` and no longer `set` (and completely undocumented).

Note that unlike how "set" worked previously, "add" will append a new webhook each time. So you either need to remove the webhook after every use or update an existing one. 

This is frustrating as it has taken quite a few hours to track down because its not documented. It's also triggered several downstream events (due to multiple webhooks being added) that now have to be cleaned up. 

As I mentioned in the previous comment it would be ace if you could release a change log. 

This change, in my opinion, ruins the previously idempotent nature of the `webhook:set` flow. Our build tools could call it once or ten times and it didn't matter. Now, we need to either store the webhook id and update the url each build, or parse the `webhooks` output and extract the ids to remove the hooks after each build run. 

I'm not against the change itself so much (it offers the advantage of having multiple hooks), but, please please start documenting these changes and expose some change log.

**Comment by jkhales** [comment]
> Just an update to the above. It is now `add` or `update` and no longer `set` (and completely undocumented).
> 
> Note that unlike how "set" worked previously, "add" will append a new webhook each time. So you either need to remove the webhook after every use or update an existing one.
> 
> This is frustrating as it has taken quite a few hours to track down because its not documented. It's also triggered several downstream events (due to multiple webhooks being added) that now have to be cleaned up.
> 
> As I mentioned in the previous comment it would be ace if you could release a change log.
> 
> This change, in my opinion, ruins the previously idempotent nature of the `webhook:set` flow. Our build tools could call it once or ten times and it didn't matter. Now, we need to either store the webhook id and update the url each build, or parse the `webhooks` output and extract the ids to remove the hooks after each build run.
> 
> I'm not against the change itself so much (it offers the advantage of having multiple hooks), but, please please start documenting these changes and expose some change log.

This is frustrating. Thanks for bringing this to our attention, I've surfaced it in the appropriate channels and we are discussing how to make sure we are better moving forward.
