### ISSUE TITLE
Allow moving webpack.config.js

### ISSUE THREAD

**Issue by hlehmann** [expo/expo-cli#1422]
Same way we can have app.json in another place `expo start --config config/my-app.json`, could it be possible to have the webpack/babel configs in another place ? Through a param in the app.json file for example ?

Nothing in the docs indicates it's possible for now.

**Comment by EvanBacon** [comment]
Due to the fragile nature of bundlers I'm going to opt towards not supporting this. 

`expo start:web` is a pretty small wrapper around Webpack CLI, so small that you can eject the webpack config and run `npx webpack` in the project root to start a project. With this in mind I think users that want a more complex bundler system should attempt to extend the Webpack CLI manually.
