### ISSUE TITLE
build:android using the wrong versionCode

### ISSUE THREAD

**Issue by magiskaoskar** [expo/expo-cli#1456]
## Description

When running `expo build:android -t app-bundle --release-channel X --non-interactive --no-publish` expo will use a lower version code than in `app.json`. In `app.json` the versionCode is set to 792 but when expo builds the app bundle it gives it versionCode 790

## Expected Behavior

When running `expo build:android` it should use the *exact* `android.versionCode` in `app.json`.

## Observed Behavior

`expo build:android` used a lower `versionCode`(790) than in `app.json` (792).

## Environment

Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 35.0.0 
      react: 16.9.0 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.59.8 
      react-navigation: ^4.0.6 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.7

Expo build service.

**Comment by magiskaoskar** [comment]
When running `expo build:android` in Bitrise(.io) it gets `versionCode` `741`.

**Comment by dsokal** [comment]
Hi @magiskaoskar!

Try running `expo build:android ...` without `--no-publish` flag. Turtle takes the value of `android.versionCode` from the latest published app to the Expo servers.

**Comment by michaek** [comment]
As it seems this behavior continues, it doesn't seem to me this should be considered closed. The value of `android.versionCode` should come from the current build, not the versionCode at the time of the last publish. The Expo configuration documentation for `android.versionCode` doesn't say it'll have no effect if you're not also publishing a release, if that's truly the desired behavior. I don't think this behavior is what a user would want, because if many things implicitly depend on a publish it really detracts from the value of a `--no-publish` flag.

I'm planning to switch to EAS builds soon, which are advertised to not publish by default, but it seems like enough people will continue to use the classic build that there's a reason to change this dependency on a publish to be more in line with user expectations.

Thanks!

**Comment by brentvatne** [comment]
this is an intended behavior, not a bug, and so we closed it. your built app with `expo build` entirely depends on what you have published, so if you skip that step we use your last published version. this explains why that is the case: https://blog.expo.io/expo-managed-workflow-in-2021-5b887bbf7dbb

i agree the behavior is somewhat confusing which is why we are moving away from it
