### ISSUE TITLE
Issue installing traveling-fastlane on windows

### ISSUE THREAD

**Issue by yogesh-singh028** [expo/expo-cli#1464]
```
npm WARN tarball tarball data for @expo/traveling-fastlane-darwin@1.11.4 (sha512-1rNq4yMHGfmYhUJuBH5lKpmHVAa5QjgXbv3MoMqsFrlnwzDaq4qHSs6s/RWHw+gmk5lASEhmW32ALArAxX9ceA==) seems to be corrupted. Trying one more time.
```

**Comment by spawluk** [comment]
I've got 

```
tarball data for @expo/traveling-fastlane-linux@1.11.4 (sha512-QFMX3XoSIBvhQ/neIE/m0wnBmeC48MEEjGsSZ1J2JdK5bHg4eWbVm7hGWqnMwV6awEjg02KaroupOqohs3NGWg==) seems to be corrupted. Trying one more time.
```

during `npm i -g expo-cli`

Env:
Windows 10 Pro
install invoked in powershell console

**Comment by bmarika** [comment]
Getting the same error too.

**Comment by goshantmeher** [comment]
error on installing expo | Win10
npm WARN tarball tarball data for @expo/traveling-fastlane-darwin@1.11.4 (sha512-1rNq4yMHGfmYhUJuBH5lKpmHVAa5QjgXbv3MoMqsFrlnwzDaq4qHSs6s/RWHw+gmk5lASEhmW32ALArAxX9ceA==) seems to be corrupted. Trying one more time.
[            ......] - extract:@expo/traveling-fastlane-linux: sill extract @expo/traveling-fastlane-linux@1.11.4 extra 

but I tried on Mac working fine.

**Comment by devPinheiro** [comment]
I spent a few days on the same issue.

**Description**
I attempted to install expo-cli on Windows 10 pro

**Expected Behaviour**
I ran npm install -g expo-cli on a Windows 10 Pro and  It should install expo cli successfully

**Observed Behavior**
Installing stopped with the following warnings

`npm WARN tarball tarball data for @expo/traveling-fastlane-darwin@1.11.4 (sha512-1rNq4yMHGfmYhUJuBH5lKpmHVAa5QjgXbv3MoMqsFrlnwzDaq4qHSs6s/RWHw+gmk5lASEhmW32ALArAxX9ceA==) seems to be corrupted. Trying one more time`

**Environment**
`Nodejs  v10.13.0`
`NPM v6.13.6`
`Windows 10 pro`

**Comment by DarkAjtix** [comment]
I have the same problem, the installation dont progress
Hope someone will find a solution (windows 10)

**Comment by matheusisquierdo** [comment]
i have the same problem too. With windows 10.

**Comment by ingenious-hans** [comment]
and me too, this is about to make me move to another way

**Comment by EvanBacon** [comment]
I've removed Fastlane in the latest version `expo-cli@4.1.0`. Installs should be far more stable on all computers now!
