### ISSUE TITLE
need to clear expo cache in the phone app, everytime i refresh code

### ISSUE THREAD

**Issue by albjeremias** [expo/expo-cli#1572]
Following the issue https://github.com/expo/expo-cli/issues/184#issuecomment-586014056

Everytime i have to load a new code.. i have to reset all the cache of the expo app in the android device with the command:
`$ adb shell pm clear host.exp.exponent`

I didn't understand what is meant by update to sdk36.. which sdk? the android-sdk? it seems there is only a version until 29 ?? 

https://developer.android.com/studio/releases/platforms#8.1
Also till which version of expo-cli and metro bundler should I upgrade? Can you be more specific.. I'm still having the same issues.

> the original reported issue was a problem with metro bundler that has been resolved - update to > sdk36 and latest expo-cli and you will be able to verify that for yourself. closing and locking this issue for that reason.
> if you have some other seemingly related issues please open a new issue and provide us with your reproducible steps as per the issue template. thanks!

## environment
$ expo --version
3.13.1
android-sdk according to android-studio:
```
SDK Components to Download: 
Android Emulator
  
295 MB
Android SDK Build-Tools 29.0.3
  
51.3 MB
Android SDK Platform 29
  
74.6 MB
Android SDK Platform-Tools
  
7.74 MB
Android SDK Tools
  
147 MB
SDK Patch Applier v4
  
1.74 MB
Sources for Android 29
  
37.6 MB
```

**Comment by brentvatne** [comment]
> I didn't understand what is meant by update to sdk36.. which sdk? the android-sdk? it seems there is only a version until 29 ??

Expo SDK 36

There still isn't really enough information for us to go off of here... Please follow the issue template:

<hr />

# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- For questions and help using Expo CLI, post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/expo-cli
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
Error text goes here!
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Also specify:

- Phone/emulator/simulator platform, model and version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.
