### ISSUE TITLE
expo client:install:android uninstalling but not installing

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1637]
```
╰─$ expo client:install:android
Could not find your Expo project. If you run this from a project, we can help pick the right Expo client version!
? Do you want to install the latest client? Yes
Uninstalling Expo from Android device.

Done!
╭─~
```

It doesn't actually download the client app or install it. The only way to install it is to run the Android app from dev tools or expo-cli interactive prompt.

cc @byCedric

**Comment by byCedric** [comment]
Thanks for pinging me! I took a look and added some extra logging. Looks like I can only reproduce this on a simulator, if and only if you _dont have expo preinstalled_. What happens is this:

1. `Android.uninstallExpoAsync` is called (in `upgradeExpoAsync`)
2. `Android.getAdbOutputAsync` is called with `['uninstall', 'host.exp.exponent']`
3. `getAdbOutputAsync` fails when Expo is not installed, added the error below.
4. The error handler of `getAdbOutputAsync` throws a new error, removing the stack trace and only reusing the message. In this instance, the message appears to be empty (might be related to `spawnAsync` not adding it).
5. An empty message is dumped to the global error logger, which only adds some blank lines
6. Execution stops because of the error

You can actually reproduce this error by running `adb uninstall host.exp.exponent` multiple times on the same device. There are two things that I can think of to improve:

1. The error handler should include the error message from `spawnAsync`'s `stderr`.
2. Either check if expo installed with `adb shell pm list packages | grep host.expo.exponent`, allow uninstall to fail during upgrade (e.g. try-catch) or switch to `adb install -r <expo.apk>` ([as mentioned here](https://stackoverflow.com/a/21634276))

What do you think? @brentvatne

**Comment by brentvatne** [comment]
> Either check if expo installed with adb shell pm list packages | grep host.expo.exponent, allow uninstall to fail during upgrade (e.g. try-catch)

Let's check if it's installed and then uninstall if so. If we check that it is installed before uninstalling and uninstall still fails, then re: your first point we can include the `stdout` and bail out, or we can match on some contents of it and provide a better error message if we know precisely what's wrong based on that message and fallback to to dumping stdout if not.

> or switch to adb install -r <expo.apk>

We also might want to keep doing `uninstall` rather than `install -r` to avoid the "signatures do not match the previously installed version; ignoring!" error which can happen if you installed from play store or built from source.
