### ISSUE TITLE
[web] - configure og meta tags 

### ISSUE THREAD

**Issue by tafelito** [expo/expo-cli#1727]
I see that in this [line](https://github.com/expo/expo-cli/blob/c2ca5ad4ad797a156b5901923714004d2bf328a2/packages/webpack-pwa-manifest-plugin/src/Metatags.ts#L2) the openGraph config is empty.

How can I extend the config to set those up? I couldn't find any documentation and by reading the code I couldn't figure it out how to replace that by extending the webpack config

**Comment by EvanBacon** [comment]
TL;DR: `expo customize:web`, select `index.html`

This was an experimental part of Expo web that I just removed in https://github.com/expo/expo-cli/pull/1686 because you may want to change these values page-by-page, so best to have them accessible outside of the build. Also it was taking something relatively simple and well documented (meta tags in the head) and making them more convoluted.

If you'd like to statically define these values you should reveal the template `web/index.html` with `expo customize:web` then add the values in the `<head />` element.

**Comment by tafelito** [comment]
what if I want to use values from the app.json to avoid duplication, like the description? I know it's a small thing, but right now some metas are generated automatically even if you customized the `index.html` and they are taking the values from the config. It's be nice to get access to those values as well like you can right now with the `WEB_TITLE`, or maybe opt out if you don't wan't expo to customize them for you?

**Comment by tiny-dancer** [comment]
@tafelito ran across this https://forums.expo.io/t/custom-webpack-config-js-define-extra-variables-in-expointerpolatehtmlplugin/41520

is this what you were looking for?

**Comment by tafelito** [comment]
@tiny-dancer I'm not so sure, a few things might have changed since I opened this issue and I haven't followed up with this. Maybe there is a way to do it now.
