### ISSUE TITLE
npm install -g expo-cli hangs on 64 bit Windows 10

### ISSUE THREAD

**Issue by cdalten** [expo/expo-cli#1819]
>npm install -g expo-cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[..................] \ fetchMetadata: WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142 

It it just has been staying at this line for the past 20 minutes.

**Comment by brentvatne** [comment]
hi there! could you look into this and try to debug it to get us more info on specifically what might be going wrong? this doesn't reproduce on our ends and so there are many factors related your particular system setup, npm installation, internet connection, location, etc that could be causing this problem. when you have had a chance to dig into it more then please create a new issue and provide us with that information. in its current form this issue is not actionable for us
