### ISSUE TITLE
Emulator Path Problem

### ISSUE THREAD

**Issue by aneff-official** [expo/expo-cli#1925]
## Description

The problem occurs when I try running an android emulator from the Metro Bundler (on localhost:19002). I have made an environmental variable ANDROID_HOME with a value of "C:\Android\Sdk", which is where my SDK is located.

## Expected Behavior

What I expect to happen is for Expo to run the emulator. When I already have an emulator up and running, there seems to be no problem to run the Expo App on it.

## Observed Behavior

There is not much else than that error message:
```
› Attempting to open emulator named: Pixel_3a
) quit before it finished opening. You can try starting the emulator manually from the terminal with: C:\Android\Sdk/emulator/emulator @Pixel_3a
```

My guess is, that it gets the paths confused somehow.

## Environment

From `expo diagnostics`:

```
  Expo CLI 3.18.4 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 13.13.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ^37.0.7 => 37.0.7
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
```

Under Windows 10 (regurlarly updated) I have the latest NPM, Node, Android Studio, with latest SDK (Android Q), running on Pixel 3a. Also, I am using Expo's latest SDK 37 and have updated Expo-cli to 3.18.4

## Screenshots

![2020-04-18 12_23_33-(4) NotifyNext on Expo Developer Tools](https://user-images.githubusercontent.com/32654709/79636994-858c2d80-8173-11ea-8e2f-1753fac864c0.png)

![2020-04-18 12_59_32-MINGW64__c_Sources_NotifyNext](https://user-images.githubusercontent.com/32654709/79637119-8a051600-8174-11ea-8771-46ecc77021cc.png)

If this is not a bug, I am sorry for posting this in here, it is my first time. I would be grateful if someone helps me fix this issue though.

Kind regards,
Chris

**Comment by aneff-official** [comment]
If this is not getting fixed, should I close the issue?

**Comment by Laetitia825** [comment]
I've got exactly the same problem. Can someone help please ? 
Thank you very much :)

**Comment by aneff-official** [comment]
It seems this issue is god-forgotten and probably not "a priority". It would be nice to get it fixed, as it does not seem too complicated although I could not get to any configuration myself.

No further details are needed to describe the problem, but if they want I am here to provide them :)

**Comment by Laetitia825** [comment]
Hi! I've just solved the problem! Actually my problem was that Expo was not downloaded by default on my virtual android device, so I downloaded it via Google Play (I opened the virtual android device on Android Studio, then I signed in my google play account and I dowloaded Expo). And then I ran my project again on Android Studio and it worked. I hope it will do also for you! 
Regards, 
Laetitia 


De: "Hristiyan Anev" <notifications@github.com> 
À: "expo/expo-cli" <expo-cli@noreply.github.com> 
Cc: "Laetitia825" <laetitia.drumare@ensta-paris.fr>, "Manual" <manual@noreply.github.com> 
Envoyé: Mercredi 20 Mai 2020 17:45:47 
Objet: Re: [expo/expo-cli] Emulator Path Problem (#1925) 





It seems this issue is god-forgotten and probably not "a priority". It would be nice to get it fixed, as it does not seem too complicated although I could not get to any configuration myself. 

No further details are needed to describe the problem, but if they want I am here to provide them :)

**Comment by aneff-official** [comment]
I am glad for you, but unfortunately I already have Expo and it still does not work.

**Comment by nnari** [comment]
I'm having the same issue trying to start my Expo app on Android via CMD.
```Trying to open the project on Android...
› Attempting to open emulator named: Pixel_3_API_28
) quit before it finished opening. You can try starting the emulator manually from the terminal with: D:\AndroidSDK/emulator/emulator @Pixel_3_API_28```

**Comment by Natetronn** [comment]
Getting this error as well.

**Comment by Jbac76** [comment]
same problem for me as well

**Comment by Zhou-Bill** [comment]
how to solve

**Comment by HeIp** [comment]
Still occurring in 2021, needs a fix.

**Comment by tiavina-mika** [comment]
Almost 2022 and not solved yet

**Comment by tatupesonen** [comment]
Bump

**Comment by Smyja** [comment]
same issue

**Comment by Armisael2k** [comment]
same problem

**Comment by Dtymchenko** [comment]
Same problem
