### ISSUE TITLE
Couldn't adb reverse: closed

### ISSUE THREAD

**Issue by wrightmk** [expo/expo-cli#198]
I'm trying to get up and running with my recently detached app.  First I run the app in Android Studio and then I try to connect my external device to Expo XDE (via usb debugging), but Expo is returning “Tunnel connected, Couldn’t adb reverse: closed”.  The external device has the error message “Could not load exp://j3-iqd.<myapp>. Are you sure XDE or exp is running?”  I've checked some of the stack overflow posts on the matter and my adb version is the same in android studio and on my local machine.  Any Idea on why this isn’t working?

**Comment by fson** [comment]
I’m closing this issue because it has been open for a long time and some of the information in this thread might not be relevant to the latest Expo CLI versions anymore.

If you're still having this issue, please [open a new issue](https://github.com/expo/expo-cli/issues/new) and make sure to provide as much information as possible (see the issue template).
