### ISSUE TITLE
Reports of `exp start` hanging

### ISSUE THREAD

**Issue by terribleben** [expo/expo-cli#199]
https://forums.expo.io/t/exp-start-hangs-in-terminal-with-no-output/5648

> steps to reproduce: not sure, it happens randomly. setting EXPO_DEBUG=true doesn’t work in this case.
> 
> Deleting ~/.expo does not work. As soon as I enter in my password it hangs at “Success. You are now logged in”.
> 
> Using latest version of exp but this has happened with older versions as well.
> 
> XDE however does work fine! I just prefer the command line.

**Comment by fson** [comment]
The update check now has a timeout for when it can't read the latest version from the npm registry, so this should be fixed in the latest Expo CLI version.

If you're still having this issue with the latest version of Expo CLI, please [open a new issue](https://github.com/expo/expo-cli/issues/new) and provide as much information as possible (see the issue template).
