### ISSUE TITLE
Web favicon images are blurry

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo-cli#2012]
maybe the order of the .ico is being generated wrong, making the 16x16 the main image

**Comment by EvanBacon** [comment]
Fixed in 0.12.2

**Comment by oguzgelal** [comment]
Hey @EvanBacon, favicons still seems to be blurry. Here's the icon I'm providing in app.json, and how it's turns out after deploy:

![wk4](https://user-images.githubusercontent.com/2817993/81487677-32843280-9268-11ea-8ed4-406e3bfd4c52.png)

<img width="68" alt="Screen Shot 2020-05-10 at 2 46 12 AM" src="https://user-images.githubusercontent.com/2817993/81487699-7840fb00-9268-11ea-9a16-7d98be46615e.png">

**Comment by andordavoti** [comment]
I have the same issue with all my projects

**Comment by barnu5** [comment]
Still having this issue as well
