### ISSUE TITLE
expo build:android throwing error

### ISSUE THREAD

**Issue by kokanek** [expo/expo-cli#2075]
## Description

Trying to build android apk using expo cli, running the command:
```
expo build:android -t apk
```

## Expected Behavior

The expected behavior is that an **apk** gets created. 

## Observed Behavior

Getting this error on running the command:

```
expo build:android -t apk
Error: could not load config json at /Users/kapeel.kokane/MyFiles/Code/goodDay/android: ConfigError: The expected pack
age.json path: /Users/kapeel.kokane/MyFiles/Code/goodDay/android/package.json does not exist
The expected package.json path: /Users/kapeel.kokane/MyFiles/Code/goodDay/android/package.json does not exist
```

## Environment

I am running the command on macos with visual studio command line.

**Comment by brentvatne** [comment]
we need more information than this. judging by the fact that you have an `android` directory i believe this is a bare project, in which case you need to build the project using android studio, we don't currently support this with the build service. also, `expo build:android` is supposed to be run from the root of a project, not from a subdirectory - so in this case it would be, i believe, from the `goodDay` directory.

anyhow if you can provide more info and convince me it's a bug i'd be happy to look into it! will close otherwise
