### ISSUE TITLE
Add expo eject --undo

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2118]
We can take care of deleting the ios/android directories and removing react-native-unimodules for people if they run this command.

**Comment by EvanBacon** [comment]
People can continue to use all of the managed features in a bare project. Managed is just a more optimal starting point. 

Further, this command seems to promise that all arbitrary changes can be undo using a single command which seems pretty fragile. 

Imo this won’t be worth the time spent building, testing, maintaining, and closing issues related to * files not being removed.

**Comment by brentvatne** [comment]
i think we can just make it work in constrained situations where all we have to do is the opposite of what we do when ejecting

```
# first, check some basic preconditions, if not met then bail out.

# delete directories
rm -rf ios android

# remove rnu
yarn remove react-native-unimodules

# add react-native version used for this sdk
yarn add react-native@version-used

# leave package.json main and metro.config.js
```

**Comment by EvanBacon** [comment]
In SDK 43, we no longer install `react-native-unimodules` or use a fork of `react-native` meaning the command would just clear the `ios` and `android` folders. I think this isn't enough functionality to justify adding to the CLI at this time, especially since we already support `expo prebuild --clean` and have moved away from `expo eject`.
