### ISSUE TITLE
Suggestion: add 'react-native-electron' to @expo/electron-adapter's webpack config

### ISSUE THREAD

**Issue by RonAmihai** [expo/expo-cli#2256]
[react-native-electron](https://github.com/PaulLeCam/react-native-electron) extends `react-native-web` with some of Electron's APIs. 

I've achieved to alias it in `@expo/electron-adapter`'s webpack config (`./electron/webpack.config.js`, created after running `yarn expo-electron customize`) using the following:
```
const { withExpoWebpack } = require('@expo/electron-adapter');

module.exports = config => {
	let expoConfig = withExpoWebpack(config);
	
	expoConfig.resolve.alias['react-native$'] = 'react-native-electron';
	
	return expoConfig;
};
```

It seems to work well, even though I guess more aliases should be added as correct setup.

It would be great if `react-native-electron` would be added to the adapter, even as optional feature.

**Comment by EvanBacon** [comment]
I'm glad you were able to get this setup and shared your findings. `react-native-electron` doesn't provide much and I don't think it makes sense to have people install it in every project. The general aliasing system used for react-native + react-native-web is already fairly complex and leads to version issues. 

After looking through the `react-native-electron` source I don't think it would makes sense because it adds new types that aren't a part of the default type system on existing methods like `Linking.openURL()`. In Expo we support multiple platforms by putting all of the types and platforms in the same package. If you'd like to add electron support to [`react-native-appearance`](https://github.com/expo/react-native-appearance) and others that would be optimal.
