### ISSUE TITLE
How to output my source map in my local dev?

### ISSUE THREAD

**Issue by SidKwok** [expo/expo-cli#257]
## Description

I would like to output my source maps via expo rather than upload them in sentry.

## Expected Behavior

Output my source maps in local dev.

## Observed Behavior

Nothing about source maps indicated in docs

## Environment

expo-cli: 2.6.11

**Comment by ide** [comment]
There isn't a way to directly export source maps but you can write your own postPublish hook that's structurally the same as the Sentry hook.

See how to specify a postPublish hook here: https://docs.expo.io/versions/latest/guides/using-sentry.html. The source code of the Sentry postPublish hook is here: https://github.com/expo/sentry-expo/blob/master/upload-sourcemaps.js. Instead of uploading the source maps, you would write them to disk instead, and then do whatever you'd like with them.
