### ISSUE TITLE
expo gives a wrong LAN address link

### ISSUE THREAD

**Issue by PeichengLiu** [expo/expo-cli#259]
Having Docker installed on my machine, expo gives a wrong LAN address link.

![Screenshot](https://i.loli.net/2018/12/14/5c13aed098673.png)

My environment:

>  Expo CLI 2.6.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - E:\Software\Util\watchman\watchman.EXE

**Comment by fson** [comment]
Expo CLI internally uses `os.networkInterfaces()` to get a list of network interfaces and then tries to sort them according to some heuristics and finally returns an IPv4 address.

Could you copy paste the full output of this command from your computer:
```sh
node -e 'console.log(os.networkInterfaces())'
```
Then hopefully we can use this to information to improve the heuristics used to select the external network interface.

**Comment by joshball** [comment]
@PeichengLiu It is because the Docker NAT interface has a higher priority, so it (node, using `os.networkInterfaces()`) is connecting to 10.0.75.1.
What you need to do is set 
`set REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.100`
Note, there still seems to be a bug where expo will continue to REPORT that it is listening on the primary (even though you have set the HOSTNAME). So you will have to manually construct your url:
exp://192.168.1.100:19000 in the expo client

**Comment by PeichengLiu** [comment]
@joshball Thanks for your note. My temporary solution is shutting down the Docker, and waiting for this issue to be fixed.

**Comment by fson** [comment]
We just released `expo-cli` version 3.3.0, which drastically improves the way we detect the correct LAN IP address. This should help with issues like this one.

If you're still having issues with IP address detection with the latest Expo CLI version, please open a another issue.
