### ISSUE TITLE
Please fix some problem in package.json template generated by "expo init" command 

### ISSUE THREAD

**Issue by DeepRolling** [expo/expo-cli#2612]
## Description
This problem is about npm package version of react-native-unimodules
The fourth parameter of FileSystem.createDownloadResumable function not called by filesystem unless the version is 0.11.0
(newest version)
but if i use the "expo init  xxx" (managed workflow) create a react-native project , i got "react-native-unimodules": "~0.10.0" . 
use https://semver.npmjs.com/ can look acceptable versions of this semantic versioning 's score ( 0.10.0 or 0.10.1) 

## Expected Behavior
please change the version of react-native-unimodules to  "react-native-unimodules": "^0.11.0" . 
and update buildToolsVersion to "29.0.2" and compileSdkVersion,targetSdkVersion to 29 (in android/build.gradle)
the sake for change android version to 29 is adapt android version of  react-native-unimodules .

## Observed Behavior
expo filesystem not call download progress callback .

## Environment
windows 10

## Reproducible Demo
this demo work fine , emmmmm , is it use react-native-unimodules 0.11.0 ?
https://snack.expo.io/@deepcode1024/brave-banana

**Comment by brentvatne** [comment]
[the latest version of react-native-unimodules is 0.10.1](https://www.npmjs.com/package/react-native-unimodules)

![Screen Shot 2020-09-13 at 12 02 45 PM](https://user-images.githubusercontent.com/90494/93026187-0c292780-f5b9-11ea-9c1c-b8d1a050b149.png)

the example you provided also works fine on react-native-unimodules@0.10.1 with expo-file-system@9.1.0: https://gist.github.com/brentvatne/66f8c20c1f5adf47ae035a9b3d19eeae - although i modified it because pressing the button wasn't actually doing anything at all in the example you shared, it was just calling an empty function.

all i did was initialize a new bare project, run `yarn add expo-file-system`, add this code to App.js and then run it and press the button. you can try it here: https://github.com/brentvatne/expo-cli-issue-2612
