### ISSUE TITLE
Error: spawn powershell ENOENT

### ISSUE THREAD

**Issue by ArtiGaund** [expo/expo-cli#2617]
PS E:\Projects\RenderApp> expo start
Starting project at E:\Projects\RenderApp
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Error: spawn powershell ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

Solution provided that 
%HOMEDRIVE%%HOMEPATH%\.expo\state.json file to add in:

  "openDevToolsAtStartup": false,
e.g. just above the “PATH” line.

But where is state.json file

**Comment by polarlightning** [comment]
I have a little different, but similar kind of problem. In my case I am using fresh install of WSL2 (Debian 10/Buster) in Windows 10 and installed expo-cli there.   I then created new minimal app  using 'expo init nr-first-app' and then trying to start it without modifications. I did not expect scripts to try starting powershell.exe in this case.  As an expo newbie I can't see what to fix and where, please help.

> @ start /home/firefox/nr-first-app
> expo start


Starting project at /home/xxxxxxx/nr-first-app
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Error: spawn powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by brentvatne** [comment]
@fson - maybe we can wrap opening the browser in try/catch so if it fails we just log that info and carry on?

**Comment by rajvishah23** [comment]
@ArtiGaund you can solve the error from here:
[https://stackoverflow.com/questions/53456639/error-spawn-cmd-enoent-in-expo-init-project](url)

**Comment by rajvishah23** [comment]
@ArtiGaund you can find the solution here
[https://stackoverflow.com/questions/53456639/error-spawn-cmd-enoent-in-expo-init-project](url)

**Comment by rajvishah23** [comment]
1- First you need to edit system environment variable and locate where you have Windows Poweshell so add new in "system environment variable path"

Add Window Powershell path in system environment variable path

2- Then Open Window PoweShell as An Administraror And Write these Two Commands :
**Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force**
**npm install --global --production npm-windows-upgrade**
:) Upgrade Window PowerShell because your nodejs and npm is updated but powershell is not updated so its making conflict with your npm start or expo start,so you should need to upgrade windows powershell

And Then run Cmd and also run your poject npm start or expo start so quickly it will work!

enter image description here

BEST OF LUCK!

**Comment by ArtiGaund** [comment]
My problem is resolved now

**Comment by ArtiGaund** [comment]
Do npm install again.
It will resolve the issue may be bz my problem was resolved by it

**Comment by EvanBacon** [comment]
This appears to be resolved in the latest, versioned Expo CLI. If you encounter this issue in the future, please open an issue on [expo/expo](https://github.com/expo/expo/issues/new?assignees=&labels=needs+review%2CCLI&template=bug_report_cli.yml).
