### ISSUE TITLE
expo start --android is launching only web view

### ISSUE THREAD

**Issue by hemanth-n-govindan** [expo/expo-cli#2634]
## Description
Expo is always launching web view but not as native android app

## Expected Behavior
Expo should launch as native app

## Observed Behavior
i launch the app with `expo start --android` which should launch app in mobile as native app, but it always launch as web view mobile browser.

![image](https://user-images.githubusercontent.com/29033042/93021686-af9e2a80-f601-11ea-9862-8c58164447c3.png)

**Comment by brentvatne** [comment]
what version of expo-cli do you have installed? can you zip your `.expo` directory inside of your project and share it?

**Comment by hemanth-n-govindan** [comment]
Thank you @brentvatne for your response. Please find attachment for complete code

[yarn.zip](https://github.com/expo/expo-cli/files/5215847/yarn.zip)

The current expo version I'm using is 3.27.4

**Comment by brentvatne** [comment]
can you run `expo diagnostics` and share the output?

**Comment by brentvatne** [comment]
@hemanth-n-govindan - can you try adding the following your app.json to add `"platforms": ["ios", "android", "web"]` and then running `expo start` again to see if that resolves your issue? (your app.json would look like this: https://gist.github.com/brentvatne/8cb2627c9383f8d4758c4834fc053b13). trying to narrow down the cause here.

**Comment by EvanBacon** [comment]
We no longer open web-only based on package installation. I can only guess that was the cause of the problem.
