### ISSUE TITLE
Expo typescript template displays white screen when opening on android(device and emulator).

### ISSUE THREAD

**Issue by Raraku** [expo/expo-cli#2680]
## Description

I did expo init and started a new typescript project. I have made no changes. I run expo start and type A for android. The expo app opens up on my phone but just displays a white page and nothing happens. The javascript bundle is also not built. Note, i have made no changes to the template.

## Expected Behavior

I expected the app to load up and show the default screens. Also, the app opens up on web but not android

## Observed Behavior

What actually happened when you performed the above actions?

```
Nothing happens, just that white screen indefinitely.
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Also specify:

- Phone/emulator/simulator platform, model and version:

 -->SDK 39. Latest version of everything

## Reproducible Demo

-> Expo init <appname>
->Choose typescript tabs
-> run expo start
-> try to run on android

**Comment by EvanBacon** [comment]
I got this error the other day and it was because the emulator stopped being able to connect to wifi. Opening Android Studio and cold booting the emulator eventually fixed the issue. If you can open pages in chrome on your emulator (`npx uri-scheme open https://github.com/expo/expo-cli/issues/2680 --android`) then this is unrelated.

**Comment by EvanBacon** [comment]
Closing as this appears to be unrelated to Expo
