### ISSUE TITLE
Cannot config scheme as array

### ISSUE THREAD

**Issue by giautm** [expo/expo-cli#2844]
In version 3.24.1, [CHANGELOG](https://github.com/expo/expo-cli/blob/master/CHANGELOG.md#-new-features-22) said expo-cli support to config scheme as array. But, Currently It still not working.

Steps to preproduce:
1) Init new project.
2) Add `"scheme": ["test1", "test2"]` to `app.json`
3) Run `expo doctor`

```
Error: Problem validating fields in app.json. See https://docs.expo.io/workflow/configuration/
 • Field: scheme - should be string.
```

_Originally posted by @giautm in https://github.com/expo/expo-cli/pull/2462#issuecomment-718969850_

**Comment by giautm** [comment]
Hey @EvanBacon, can you take a look?

**Comment by EvanBacon** [comment]
It's not part of [the official schema](https://github.com/expo/expo-cli/blob/69c353fb63150cd123673d1ba5fea587e5f9a135/packages/config-types/src/ExpoConfig.ts#L158). It was only added to `expo eject` because our v1 build service does the following `[expo.scheme, expo.ios.bundleIdentifier]` (and similar on Android) this is to support Google authentication. 

In the v2 build service we will eject the project in the cloud, essentially adding support for scheme arrays. But it's too tricky to add backwards compat reliably right now so I've opted to leave it out of the official schema.

Build v2 should be available sometime in December.

**Comment by giautm** [comment]
> In the v2 build service we will eject the project in the cloud
Wow! Sound like, native module will be supported by Build v2. 🤔

**Comment by AlbertoCabreraJr** [comment]
any updates on this?
