### ISSUE TITLE
Authenticating to Apple Developer Portal does not work on macOS Big Sur

### ISSUE THREAD

**Issue by sgehrig** [expo/expo-cli#2954]
## Description

Authenticating to Apple Developer Portal does not work on macOS Big Sur any more. See here as well: https://forums.expo.io/t/expoios-fails-after-updated-to-macos-big-sur/45824

## Expected Behavior

Authenticating to Apple Developer Portal works as before with macOS versions earlier than Big Sur.

## Observed Behavior

Authenticating to Apple Developer Portal does not work on macOS Big Sur.

```
Using password from your local Keychain. Learn more https://docs.expo.io/distribution/security#keychain
Authenticating to Apple Developer Portal...
Available session is not valid any more. Continuing with normal login.
No route to host - connect(2) for "appstoreconnect.apple.com" port 443
Authentication with Apple Developer Portal failed!
Reason: Unknown reason, raw: "Could not receive latest API key from App Store Connect, this might be a server issue."
Error: Reason: Unknown reason, raw: "Could not receive latest API key from App Store Connect, this might be a server issue."
    at runAction (/usr/local/lib/node_modules/expo-cli/src/appleApi/fastlane.ts:28:17)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at authenticate (/usr/local/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:49:40)
    at Context.ensureAppleCtx (/usr/local/lib/node_modules/expo-cli/src/credentials/context.ts:81:24)
    at IOSBuilder.bestEffortAppleCtx (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:95:14)
    at IOSBuilder.prepareCredentials (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:151:5)
    at IOSBuilder.run (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:62:7)
    at IOSBuilder.command (/usr/local/lib/node_modules/expo-cli/src/commands/build/BaseBuilder.ts:39:7)
    at Command.<anonymous> (/usr/local/lib/node_modules/expo-cli/src/exp.ts:332:7)
```

## Environment

```
Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.3.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.9 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed
```

**Comment by sgehrig** [comment]
@butimo FYI

**Comment by butimo** [comment]
As additional information. This environment was working pretty fine with macOS Catalina and after updating to Big Sur, just build:ios -> archive is failing

**Comment by EvanBacon** [comment]
Appears to be a Fastlane permissions error https://github.com/fastlane/fastlane/issues/14750

**Comment by butimo** [comment]
Tried this morning with expo 4.0.1, still failing. Is there a workaround?

  ```
Expo CLI 4.0.1 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.3.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.9 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 4.0.1
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
the error message from OP sounds like a network issue that we can't do much about:

> No route to host - connect(2) for "appstoreconnect.apple.com" port 443

perhaps try changing dns? you could try google public dns for example

**Comment by brentvatne** [comment]
@ide tested this on his machine on big sur and had no issues, so i strongly suspect it's a network issue on your end

**Comment by ide** [comment]
I tested on Big Sur 11.0.1 and was able to log in with my Apple developer credentials without any issues. I'm not running any kind of networking software such as Little Snitch or a VPN, don't have any HTTP proxies (no `http_proxy` or `https_proxy`), and the router just has a basic NAT firewall. No country-/state-level connectivity issues or IP blocks. The only customization is that DNS is overridden in macOS's networking preferences to use Cloudflare.

**Networking:** For the networking issues, I would test that you can access these domains: https://github.com/fastlane/fastlane/blob/master/spaceship/README.md#api-endpoints. Use cURL or something in a terminal for more parity with how Expo CLI would run.
```
https://idmsa.apple.com
https://developerservices2.apple.com
https://developer.apple.com
https://appstoreconnect.apple.com
https://du-itc.appstoreconnect.apple.com
https://is[1-9]-ssl.mzstatic.com
```

Big Sur did make some changes to networking, so I'd also check if disabling apps like Little Snitch, Charles Proxy, etc... helps. It might be completely unrelated, but there have been some issues with networking apps like that.

**Fastlane/Apple session:** In case the issue can be fixed by generating a new Apple login session, try clearing `~/.fastlane/spaceship/{appleid}/cookie`. This will force Fastlane to log in to Apple again, prompting you for your 2FA code.

If you want to go even further, you can delete your Apple developer password from your keychain. I found mine under the `login` keychain > Passwords > an entry named `deliver.{appleid}`.

**Comment by butimo** [comment]
Sorry guys. Face palm :-(
That was the missing link. I must have disallow ruby on Little Snitch when updating it for Big Sur.
Sorry again. All works fine now. You can close the issue.
