### ISSUE TITLE
Ejecting app doesn't completely setup linking for iOS

### ISSUE THREAD

**Issue by hardcodet** [expo/expo-cli#3007]
## Description

I noticed that pressing an app link only focused my app on iOS if the app was already running in the background, rather than firing the link event listener. Turns out that the snippets documented at https://reactnative.dev/docs/0.60/linking were not added to `AppDelegate.m`.

That should be an easy fix, but will safe every developer running into this the headache of triangulating and fixing the issue.

```
// iOS 9.x or newer
#import <React/RCTLinkingManager.h>

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

And for universal links, also:

```
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}
```

**Comment by EvanBacon** [comment]
Generally speaking, we don't support modifying the AppDelegate or other application code because it's not a safe, or predictable change. Our template AppDelegate is based on the [react-native default template](https://github.com/facebook/react-native/blob/master/template/ios/HelloWorld/AppDelegate.m) which doesn't support the proposed method by default. 

In Unimodules, users have control over AppDelegate methods without needing to modify the AppDelegate directly. This is the direction we want to move in so users can just `yarn add X` and not have any extra native modifications required.
