### ISSUE TITLE
"expo upgrade" could offer an interactive mode to prompt before changing package versions in bare apps

### ISSUE THREAD

**Issue by hardcodet** [expo/expo-cli#3015]
## Description

Minor issue!

expo 39 -> 40

Ran `expo upgrade` on my bare (ejected) project. A few observations of package downgrades that maybe could be avoided. After all, you can assume that the developer did choose that particular package on purpose:

![image](https://user-images.githubusercontent.com/873009/101781327-efd55200-3af7-11eb-9ec6-b2b74fbcf691.png)

**Comment by hardcodet** [comment]
Addendum: Looks like expo upgrade didn't upgrade me to SDK 40, I'm still stuck on 39. ran it again, now it switched to 40.0.0.

**Comment by brentvatne** [comment]
i think we discussed this somewhere else, but i don't remember where. `expo upgrade` picks the versions of packages that are compatible with the sdk version you're moving to. you can review the diff and keep changes or revert them if you want. i think we could have some kind of interactive upgrade that lets you decide at the time of running the command to update a package or not, but at the moment this is expected behavior

**Comment by SrBrahma** [comment]
@brentvatne `yarn` has a cool `yarn upgrade-interactive` that works perfectly in monorepos. I found this issue in Google searching for `expo upgrade interactive`. Would be awesome if it worked similarly but limiting the version of the packages according to Expo.

**Comment by SrBrahma** [comment]
Still valid

**Comment by kbrandwijk** [comment]
If you think the feature request is still valid, then please open one on https://expo.canny.io/. Thank you!
