### ISSUE TITLE
console.debug over a certain size generates PayloadTooLargeError

### ISSUE THREAD

**Issue by kevgrig** [expo/expo-cli#3051]
## Description

Calling `console.debug` with a string over approximately 103,000 characters long causes a `PayloadTooLargeError`. I did a binary search on the size but it turns out it's not deterministic across runs. If you try 102,000, it seems to always work fine.

## Environment

```
$ expo diagnostics

  Expo CLI 4.0.17 environment info:
    System:
      OS: Linux 5.9 Fedora 33 (Workstation Edition) 33 (Workstation Edition)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.15.1 - /usr/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 6.14.8 - /usr/bin/npm
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.27.4
    Expo Workflow: managed
```

- Phone/emulator/simulator platform, model and version: Android emulator (Pixel_2_API_30)

## Expected Behavior

If there's some limit in Expo, print a warning or truncate instead. For a long time, I thought my code was causing this error and it took me a while to figure out that it wasn't. This issue also seems to sometimes cause some buffered debug to be lost and I was pulling my hair out trying to figure out why some debug wasn't being printed at all (i.e. not even debug that involved long strings). At first, I thought this was related to https://github.com/expo/expo/issues/4340 but it doesn't appear to be.

## Observed Behavior

```
PayloadTooLargeError: request entity too large
    at readStream (/usr/local/share/.config/yarn/global/node_modules/raw-body/index.js:155:17)
    at getRawBody (/usr/local/share/.config/yarn/global/node_modules/raw-body/index.js:108:12)
    at read (/usr/local/share/.config/yarn/global/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/usr/local/share/.config/yarn/global/node_modules/body-parser/lib/types/json.js:135:5)
    at call (/usr/local/share/.config/yarn/global/node_modules/connect/index.js:239:7)
    at next (/usr/local/share/.config/yarn/global/node_modules/connect/index.js:183:5)
    at serveStatic (/usr/local/share/.config/yarn/global/node_modules/serve-static/index.js:75:16)
    at call (/usr/local/share/.config/yarn/global/node_modules/connect/index.js:239:7)
    at next (/usr/local/share/.config/yarn/global/node_modules/connect/index.js:183:5)
    at call (/usr/local/share/.config/yarn/global/node_modules/connect/index.js:248:3)
```

## Reproducible Demo

```
import React from 'react';
import { Text, View } from 'react-native';

export default function App() {
  console.debug("App started");
  const str = new Array(103000).join("=");
  console.debug(str);
  console.debug("Large debug completed");
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Hello World</Text>
    </View>
  );
}
```

**Comment by fson** [comment]
Empirically, the current maximum length for a string is 102,322 characters, after that you get the error `PayloadTooLargeError: request entity too large`.

For other types than strings that are serialized with `pretty-format`, we already set the limit of 10,000 characters on the client side, so the output is truncated at 10,000 characters and the string "...(truncated to the first 10000 characters)" appended to it.

We should probably truncate strings the on the client, the same way as these serialized objects.

**Comment by fson** [comment]
Made a fix for this on the client side, https://github.com/expo/expo/pull/11776. This should ensure long strings are truncated. I think there's still a small possibility of getting this error, since you could pass many strings like `console.log(arg1, arg2, arg3)` and in some cases many log entries might be batched in one request, but since the limit on the server side is roughly 10x the client-side limit, this should be quite rare.

**Comment by kevgrig** [comment]
Thanks!

**Comment by cederom** [comment]
I still get this error. No truncate. I need to see these data for short development while. How can I change limit?

**Comment by flexa-david** [comment]
This error has been plaguing my life for the last year and I finally decided to look into it - as everywhere seems to be attributing console.log string limit, however it turns out that is not the [only] issue.

Essentially expo dev-server needs to set a body-parser limit which it doesn't, and that defaults to 102400 byte limit for json response body when using fetch. Body parser uses "10kb" as default limit and parses it to bytes `bytes.parse('100kb') === 102400`.

The error is actually originating from `raw-body` which is being used under the hood by `body-parser` `read()` which body-parser json() uses.

I've been created a pull request that makes the body-parser limit configurable via Expo config. This threads through to the createDevServerMiddleware function in `expo/dev-server/build/middleware/devServerMiddleware.js` i.e.

`middleware.use(body_parser_1.default.json({ limit: '50mb' }));`

Perhaps there was a reason why this wasn't set larger, however it has resolved the issue entirely for me.

Review PR at https://github.com/expo/expo-cli/pull/4094/files

**Comment by davidtedmanjones** [comment]
This error has been plaguing my life for the last year and I finally decided to look into it - as everywhere seems to be attributing console.log string limit, however it turns out that is not the [only] issue.

Essentially expo dev-server needs to set a body-parser limit which it doesn't, and that defaults to 102400 byte limit for json response body when using fetch. Body parser uses "10kb" as default limit and parses it to bytes `bytes.parse('100kb') === 102400`.

The error is actually originating from `raw-body` which is being used under the hood by `body-parser` `read()` which body-parser json() uses.

I've created a pull request that makes the body-parser limit configurable via Expo config. This threads through to the createDevServerMiddleware function in `expo/dev-server/build/middleware/devServerMiddleware.js` i.e.

`middleware.use(body_parser_1.default.json({ limit: '50mb' }));`

Perhaps there was a reason why this wasn't set larger, however it has resolved the issue entirely for me.

Review PR at https://github.com/expo/expo-cli/pull/4094/files

**Comment by gretzky** [comment]
I'm still getting this error, any way we can push this PR through?

**Comment by EvanBacon** [comment]
This is resolved in the latest, versioned Expo CLI. Now there is no limit as we stream over WebSockets. If you encounter this issue in the future, please open an issue on [expo/expo](https://github.com/expo/expo/issues/new?assignees=&labels=needs+review%2CCLI&template=bug_report_cli.yml).

**Comment by jameswilddev** [comment]
@EvanBacon Which version was this fixed in?

**Comment by EvanBacon** [comment]
It’s fixed in “npx expo” for SDK 46. It will not be backported to expo-cli.
