### ISSUE TITLE
Expo Developer Tools is disconnected from Expo CLI. Use the expo start command to start the CLI again

### ISSUE THREAD

**Issue by rohyadav** [expo/expo-cli#3084]
😈 >expo start
Starting project at /Users/rohit/@Home/Workspace/React_Native/weather-app
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Starting Metro Bundler

 exp://192.168.43.27:19000
 > QR Code here

To run the app, choose one of:
 › Scan the QR code above with the Expo app (Android) or the Camera app (iOS).
 › Press a for Android emulator, or i for iOS simulator, or
    w to run on web.
 › Press e to send a link to your phone with email.

Press ? to show a list of all available commands.
Logs for your project will appear below. Press Ctrl+C to exit.
Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)

-----------------------

Getting above error: 
What is have done so far for fix this.
```javascript
npm uninstall -g expo-cli && npm i -g expo-cli
```
delete the node_modules and package.lock.json file as-well and then ***npm install**
and after so many tries same issue.
how can i fix this. even earlier it was working but suddenly doing a dev.  after rebuilding getting this issue.

expo version:- 4.0.17
node version: - v14.15.3 
npm version:- 6.14.9
OS:- MacOs Catalina

**Comment by spike0161** [comment]
I am experiencing the exact same issue. I am running the same versions of expo, node, and npm and my OS is bigSur. I have uninstalled and re-installed globally expo-cli. Removed the node modules and package-lock.json and npm install again. I have read that "watchman" might need to be installed but I had no success with that package either. Any tips or advice would be very much appreciated

**Comment by eadurflinger** [comment]
I'm also having this issue. It was working 2 days ago, but upon starting back up this morning I'm getting the same error. I uninstalled then re-installed the expo-cli globally, deleted my node modules and package-lock.json, npm installed, but to no avail. 

expo version: 4.0.17
node version: v12.19.0
npm version: 6.14.8
OS:- MacOs Catalina

**Comment by yaralavazhaLa** [comment]
I ran the following commands in the order:

npm install
brew update
brew install watchman
expo start 

And it worked !

**Comment by rohyadav** [comment]
For me watchman is not installing. 
event though earlier that was working using **expo start** suddenly it stoped working. I have removed **node_modules** and .lock.json file as well tried multiple times but still not luck same issue.
My question is why so many person have a same issue. is there any stable fixed for this. because this issue is very old.

**Comment by brentvatne** [comment]
@rohyadav - because watchman is required to use react-native on macos, and so this applies to expo as well. we list it in our installation instructions: https://docs.expo.io/get-started/installation/#1-expo-cli

you may be able to get away with not having watchman for a bit depending on how big your project is and what your file watcher limit is set to, but eventually it will likely be needed.

you can see that the same issue occurs on create-react-app: https://github.com/facebook/create-react-app/issues/4540 - as well as many other projects. you can google the error to find many more.

if you are having trouble installing watchman, you can share more information here and we may be able to help, but someone has likely encountered the same error already and reported it to the watchman issues.

watchman installation instructions: https://facebook.github.io/watchman/docs/install.html
watchman issues: https://github.com/facebook/watchman/issues

**Comment by abderrahimel** [comment]
deleted my node modules and package-lock.json
npm install
expo start
