### ISSUE TITLE
Expo not updating.

### ISSUE THREAD

**Issue by Ladvace** [expo/expo-cli#3114]
I'm trying to start an application made with `expo init`  with the command `yarn web`, every time I do that I get the message:

**You are currently using expo-cli 3.4.1**

the problem is that I have already updated it, in fact, if I check the version with `expo-cli --version` I get the last version and not the one in the message.

_I need to fix that because I get an error while starting the application and I think it's due to the outdated version._

**Comment by byCedric** [comment]
Hi @Ladvace, it looks like you could be using a local _and_ globally installed Expo CLI. If you run `yarn why expo-cli`, you could check if there is a specific version used in your project. If so, remove it :) If that doesn't help, you could check if you installed `expo-cli` twice (with NPM and Yarn). I would suggest only installing it with Yarn, remove it from NPM.

Alternatively, you could work around the issue to start Expo from a Docker instance. That helps you to start from a clean environment, one you are certain there is only 1 version of the Expo CLI installed.

Because this is related to your local environment setup, there isn't a lot we can do to help you further. If you can't figure it out, it might be good to "reset" your Node setup. (e.g. removing Node, with all NPM/Yarn packages to start over)
