### ISSUE TITLE
"expo is not installed": error message is confusing when the error is due to user needing to run npm install

### ISSUE THREAD

**Issue by fson** [expo/expo-cli#3147]
## Description

Missing `node_modules` folder causes this error:
> `expo` is not installed. Please install it with `yarn add expo` and try again.

## Environment
```
  Expo CLI 4.1.3 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.13.0 - /var/folders/vm/7_1sz9n56yj8d6v_dl1xpdf80000gn/T/fnm-shell-8134368/bin/node
      Yarn: 1.18.0 - /var/folders/vm/7_1sz9n56yj8d6v_dl1xpdf80000gn/T/fnm-shell-8134368/bin/yarn
      npm: 6.14.11 - /var/folders/vm/7_1sz9n56yj8d6v_dl1xpdf80000gn/T/fnm-shell-8134368/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 4.1.3
    Expo Workflow: managed
```

## Expected Behavior

Should print the normal node-modules-not-found-error `node_modules directory is missing. Please run \`npm install\` in your project directory.` instead.

## Observed Behavior

```
Cannot determine which native SDK version your project uses because the module `expo` is not installed. Please install it with `yarn add expo` and try again.
    ├─ getExpoSDKVersion /Users/ville/Projects/expo-cli/packages/config/src/Project.ts:23:9
    ├─ ensureConfigHasDefaultValues /Users/ville/Projects/expo-cli/packages/config/src/Config.ts:496:18
    ├─ fillAndReturnConfig /Users/ville/Projects/expo-cli/packages/config/src/Config.ts:109:10
    ├─ getConfig /Users/ville/Projects/expo-cli/packages/config/src/Config.ts:185:10
    ├─ configureProjectAsync /Users/ville/Projects/expo-cli/packages/expo-cli/src/commands/start.ts:304:25
    ├─ action /Users/ville/Projects/expo-cli/packages/expo-cli/src/commands/start.ts:173:34
    ├─ /Users/ville/Projects/expo-cli/packages/expo-cli/src/commands/start.ts:351:16
    └─ expo start /Users/ville/Projects/expo-cli/packages/expo-cli/src/exp.ts:346:7
```
But `expo` was included in the project dependencies:
```
"expo": "^39.0.0",
```
The actual problem was that I just forgot to run `yarn` before starting the dev server, but Expo CLI detected that as missing `expo` dependency and suggested running `yarn add expo` (which would have updated it to a different version, if I had done it).

## Reproducible Demo

Clone the React Navigation example project from GitHub and run `expo start`.

**Comment by brentvatne** [comment]
similar to https://github.com/expo/expo-cli/issues/2980 but i think this particular issue report is clearer so i will close mine

**Comment by EvanBacon** [comment]
Technically this isn't misleading, expo cannot be found. We cannot simply "check for the node_modules folder" because the user could be running in a monorepo, in which case the node_modules folder would be somewhere other than the project root. All we can detect is if the module can be resolved or not, this error message reflects that.

**Comment by brentvatne** [comment]
it's true that there is some edge case where if you use yarn workspaces and every single dependency in your app is hoisted, then you may not have a node_modules directory. however, if you even have a single dependencies that includes a bin you will still end up with node_modules/.bin.

regardless of the technical details there, i think it's fair to say that we probably should not depend on node_modules existing as that may break things in the future. so, instead i think we should improve the error message in this case.

the most common reason for seeing "Cannot determine which native SDK version your project uses because the module `expo` is not installed. Please install it with `yarn add expo` and try again." right now would be that the has not yet run `yarn` or `npm install`. so we should lead with that.

**Comment by fson** [comment]
We should also be able to check the dependencies in `${workspaceRoot}/package.json` and `${projectRoot}/package.json` – if neither has the `expo` dependency, then indeed it's missing and the correct fix might be running `yarn add expo` (although they must be careful to add the correct version). In other cases the correct fix is likely running `yarn` / `npm install`.
