### ISSUE TITLE
Installing the CLI gives a lot of warnings

### ISSUE THREAD

**Issue by singhayushh** [expo/expo-cli#3225]
Hello, 
When I recently tried to install the expo-cli using the command `npm install -g expo-cli`, there were a total of 27 warnings shown for some deprecated packages and dependencies being used. Some of them even had the label `Unsupported platform` and I am not sure of what to do.

I am using Kubuntu (20.04 LTS)

Here's the log:
https://pastebin.com/FH0KrPt8

**Comment by EvanBacon** [comment]
These packages cannot be upgraded because they recommended upgrade does not support Node 10 (LTS). 
```
npm WARN deprecated @hapi/joi@17.1.1: Switch to 'npm install joi'
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated @hapi/formula@2.0.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated @hapi/pinpoint@2.0.0: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/address@4.1.0: Moved to 'npm install @sideway/address'
```

**Comment by brentvatne** [comment]
we resolve these warnings when we can but we don't always have control over the ability to upgrade dependencies right away. usually the warnings you see are from distant downstream dependencies, eg: expo-cli depends on a which depends on x which depends on y which depends on z. we have to wait for a to update their dependency on x which results in updating y and z. this is just a common thing you will see in the node ecosystem due to the way warnings are exposed to users (i disagree with this approach, but that's my own opinion). we update dependencies whenever it makes sense to, and we do that frequently.
