### ISSUE TITLE
running the ios simulator on windows

### ISSUE THREAD

**Issue by 13Lulu13** [expo/expo-cli#3527]
WARNING: expo-cli has not yet been tested against Node.js v16.2.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)

**Comment by byCedric** [comment]
Hi @13Lulu13! I'm not sure if I understand what problem you are encountering.

- The node version is already fixed in the latest `expo-cli`, if you upgrade to `4.5.0` this should be gone.
- It's currently not possible to run the iOS simulator on Windows, because Apple doesn't support it.

Hope this helps!

**Comment by 13Lulu13** [comment]
Hi @byCedric thank you for your reply, Tell me please what is the alternative, because I am working on a project for android and iOS apps development, and I am working on Windows. What else can I use for the development, because some of my collegues told me that it is possible, because react native is creating the working environment just after typing the exact commands for ios. The problem is that my friend is not available at the moment to help me...
