### ISSUE TITLE
console.log statements not showing when using `expo run:ios` in bare react-native app

### ISSUE THREAD

**Issue by mwarger** [expo/expo-cli#3605]
When using `expo run:ios` with a non-expo react-native application, console logs are not printing.

With the standard `react-native run-ios` command, they are shown as expected.

I'm not sure if this is a bug or expected.  Is there an additional setup needed to see the output with a "bare" react-native application when using the expo run commands?

Thank you.

**Comment by EvanBacon** [comment]
Yes, expo run:android and expo run:ios are for projects using expo. In order to support the Expo Go app (and dev clients) we need to filter logs based on whichever bundle is currently running in a native runtime. 
To get this working, to one of the following:

- Install `expo` and import `import 'expo'` or use the app entry (most non intrusive method).
- Install and configure `expo-dev-client` (a bit more of a managed experienced).

**Comment by mwarger** [comment]
> * Install `expo` and import `import 'expo'` or use the app entry (most non intrusive method).

Would you be able to provide more detail about what you mean by this?
