### ISSUE TITLE
Smarter Yarn Install Logic (Remote Build Broken for Workspaces)

### ISSUE THREAD

**Issue by parisholley** [expo/expo-cli#3716]
### Summary

if a project is using yarn workspaces, you can never run yarn install from a sub directory, it always has to be in the project root, otherwise, you risk having multiple versions of react (and other dependencies too) and thus, invariant errors (additionally in my case, some dependencies do not like being ran from sub directory, hence my eas build problems).

this logic needs to be ported from EAS build CLI to general CLI
https://github.com/expo/eas-build/blob/82b6c2759f5217309d44788c13b507d09366709e/packages/build-tools/src/utils/project.ts#L58

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 30.0.0, 30.0.1
        System Images: android-28 | Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

iOS

### Error output

[stderr] error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/Users/expo/workingdir/build/client/mobile/node_modules/@react-native-community/cli-platform-ios/node_modules/xcode/node_modules'"

### Reproducible demo or steps to reproduce from a blank project

https://github.com/parisholley/expo-bugs

**Comment by parisholley** [comment]
for anyone running into this issue, as of now, there is no way to work around this in EAS builds, you will have to fallback to expo (not eas) cli and archive locally (or in your CI) and then publish to stores yourself.

``expo build:ios --release-channel production -t archive``

**Comment by wkozyra95** [comment]
eas-cli is in https://github.com/expo/eas-cli/ , please post all issues realted to eas build there

> if a project is using yarn workspaces, you can never run yarn install from a sub directory,

behavior of yarn install should not be the same regardless of the directory you are calling it from if workspaces are setup correctly

> some dependencies do not like being ran from sub directory, 

can you clarify that and give some examples?

> this logic needs to be ported from EAS build CLI to general CLI
https://github.com/expo/eas-build/blob/82b6c2759f5217309d44788c13b507d09366709e/packages/build-tools/src/utils/project.ts#L58

this is the code that is used for eas build both for local builds `eas build --local` and for remote builds.

> Reproducible demo or steps to reproduce from a blank project
>
>https://github.com/parisholley/expo-bugs

- you are comparing here `expo start` (it builds just js bundle) with `expo run:ios` (eject and build on the fly) it's still possible that the project is incorrect if `expo start` works because all the native code is not used
- this example does not show anything about eas build, there is no eas.json there so project is not even configured for building using eas

**Comment by brentvatne** [comment]
sent this pr to your repo to fix workspace configuration issues: https://github.com/parisholley/expo-bugs/pull/1
