### ISSUE TITLE
Failed to update expo-cli from 2.10.1 to 2.11.1

### ISSUE THREAD

**Issue by spyshower** [expo/expo-cli#386]
Error messages:

<img width="564" alt="screenshot 2019-02-21 at 17 31 52" src="https://user-images.githubusercontent.com/7046283/53180622-9cca9c00-35fe-11e9-95ba-559de286f704.png">

<img width="557" alt="screenshot 2019-02-21 at 17 29 41" src="https://user-images.githubusercontent.com/7046283/53180471-4c533e80-35fe-11e9-94a1-6e720c5f4863.png">

I tried manually installing node-pty-built, but that didn't change the result from installing expo-cli.

Now I can't run expo-cli and can't start an Expo project.

**Comment by wkozyra95** [comment]
Hi
Until this is resolved I suggest downgrading back to 2.10.1 or switching to nvm.

**Comment by spyshower** [comment]
> Hi
> Until this is resolved I suggest downgrading back to 2.10.1 or switching to nvm.

It seems I still get this error and it doesn't want to go away...

**Comment by asherwebb** [comment]
I have the same issue and downgrading to 2.10.1 gives me the same error

**Comment by wkozyra95** [comment]
You can try removing expo-cli manually from global node_modules directory, @spyshower in your case it's `rm -r /usr/local/lib/node_modules/expo-cli`(and the same with `node-pty-prebuilt` if you installed it separately). From the error message, it's clearly permission issue so `sudo` should work (normally I wouldn't advise that but since it's already installed globally)

2.10.1 does not have that dependency so downgrade shouldn't be a problem, can you post exact commands you used to install it originally and to downgrade it?
I tried to repoduce this problem with node from nvm, homebrew and downloaded from node website and there were no issues. Is there anything specyfic about you system that could cause that, how did you install node?

**Comment by asherwebb** [comment]
as a follow up I did get it installed with `sudo npm i expo-cli -g --unsafe-perm` as a workaround it likely is some sort of conflict specific to local permissions

**Comment by spyshower** [comment]
@wkozyra95,

I used `sudo npm i -g expo-cli` to update it originally, and I used `sudo npm uninstall -g expo-cli` to remove it, then `sudo npm i -g expo-cli@2.10.1` to install it again.

Right now, there is no expo-cli folder in the path you specified, because I removed it with the above command I guess.

Lastly, I don't really remember how I installed Node but this has never been a problem for me.

**Comment by edoantonioco** [comment]
@asherwebb fix does works, thanks a lot. And I hope expo devs fix it soon.

**Comment by wkozyra95** [comment]
Hi @edoantonioco 
It's not really expo issue and we can't really fix that other than not using this package. I'm going to make this dependency optional so it won't crash during install,  but commands that are using it won't work(currently only switching to app signing by google play is using it).

**Comment by wkozyra95** [comment]
Released v2.11.2
