### ISSUE TITLE
Converting react native project into expo

### ISSUE THREAD

**Issue by princepeanut** [expo/expo-cli#410]
is that any way to converting react native project into expo

**Comment by ngode1** [comment]
This link should explain how to migrate CRNA over to the Expo CLI.

**Expo & "Create React Native App"**
https://docs.expo.io/versions/latest/workflow/create-react-native-app/

**Comment by cruzach** [comment]
Hey @princepeanut ,

As @ngode1's link says, "All apps created with `create-react-native-app`, are compatible with Expo CLI without changes."

You can follow the steps [here](https://github.com/react-community/create-react-native-app/blob/master/CHANGELOG.md#upgrading-from-1140-to-201) to migrate from CRNA to the Expo CLI.

Let me know if that answers your question

**Comment by AdamJNavarro** [comment]
As @ngode1 and @cruzach alluded to above, there are migration steps that you can follow to convert your project. I'm going to close this issue as we aim to reserve Github issues strictly for bug reports rather than questions. If you have any further questions, please don't hesitate to post on our [forums](https://forums.expo.io/)!

Cheers,
Adam
