### ISSUE TITLE
"expo init <project>" should add an empty "description" attribute in "app.json"

### ISSUE THREAD

**Issue by warren-bank** [expo/expo-cli#420]
it seems that most of the published projects have no description.. this would probably help by making it more obvious where/how to add one.

to take this suggestion one step farther..
since `expo init` prompts the user (in an interactive shell) to enter values for the fields `name` and `slug`..
the same could be done for the `description` field.

**Comment by brentvatne** [comment]
hello! i think this made a lot of sense when we were thinking about expo more as a social platform.

these days we are moving away from social platform / sharing aspects of expo and focusing on expo as a developer tool for building and shipping apps on the app stores. the 'description' field is mainly intended for giving people some information about your project if they happen to stumble upon it when searching on the website. we also want to ideally simplify init so that people aren't prompted for the slug, because that's more information than they really need to provide when they are just writing a hello world app (https://github.com/expo/expo-cli/issues/1240)

thanks for the feedback, i think it was a very reasonable suggestion at the time :)
