### ISSUE TITLE
Update node engine to support node 17+

### ISSUE THREAD

**Issue by jim-junior** [expo/expo-cli#4332]
I was requesting that the authors of expo would please update `expo-cli` to support latest versions of node.
I was trying to install the cli but i keep getting the error that my node engine is not supported. I am using node `v17.9.0`

**Comment by EvanBacon** [comment]
We are limiting the version due to react-native/metro not supporting 17. You may notice that react-native cli has issues/errors that are thrown when using the latest node.

<img width="1012" alt="Screen Shot 2022-04-12 at 12 21 37 PM" src="https://user-images.githubusercontent.com/9664363/165139937-9f01a213-d1ee-4500-afc1-08e4000c5915.png">

**Comment by jim-junior** [comment]
Okay I get it now
