### ISSUE TITLE
expo run:android uses yarn even if there is a package-lock.json and no yarn.lock

### ISSUE THREAD

**Issue by wodin** [expo/expo-cli#4355]
### Summary

As Brent says [here](https://forums.expo.dev/t/android-failure-for-managed-workflows-due-to-npm/63576/8?u=wodin):

> it appears that the default logic when running expo run:android defaults to using yarn if you have it installed, rather than checking for lockfile as it should

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.13.2 - ~/bin/node
      Yarn: 1.22.18 - ~/.npm-global/bin/yarn
      npm: 8.9.0 - ~/.npm-global/bin/npm
    npmPackages:
      expo: ~45.0.0 => 45.0.1 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

🧶 Using Yarn to install packages. Pass --npm to use npm instead.

### Reproducible demo or steps to reproduce from a blank project

```
/tmp$ expo init blah -t blank --npm
✔ Downloaded template.
📦 Using npm to install packages.
✔ Installed JavaScript dependencies.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following npm commands.

- cd blah
- npm start # you can open iOS, Android, or web from here, or run them directly with the commands below.
- npm run android
- npm run ios # requires an iOS device or macOS for access to an iOS simulator
- npm run web
/tmp$ cd blah
/tmp/blah$ ls -l
total 359
-rw-r--r--   1 michael michael    454 1985-10-26 10:15 App.js
-rw-r--r--   1 michael michael    675 2022-05-09 13:09 app.json
drwxrwxr-x   2 michael michael      6 2022-05-09 13:09 assets
-rw-r--r--   1 michael michael    107 1985-10-26 10:15 babel.config.js
drwxrwxr-x 593 michael michael    594 2022-05-09 13:10 node_modules
-rw-r--r--   1 michael michael    530 2022-05-09 13:09 package.json
-rw-rw-r--   1 michael michael 865783 2022-05-09 13:10 package-lock.json
/tmp/blah$ yarn --version
1.22.18
/tmp/blah$ expo run:android

📝  Android package Learn more.

✔ What would you like your Android package name to be? … com.example.blah
✔ Created native project
✔ Added Metro config
✔ Updated package.json and added index.js entry point for iOS and Android
› Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead

🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies 152682ms
» android: userInterfaceStyle: Install expo-system-ui in your project to enable this feature.
✔ Config synced
› Opening emulator Pixel_4_API_30
› Building app...
```

**Comment by ger88555** [comment]
I am having the same problem. On an Expo project using NPM, the `expo run:android` command doesn't work anymore.

Despite having a `package-lock.json` and no `yarn.lock` in the project root, the command will attempt to prebuild using **Yarn**.

---

>🧶 Using Yarn to install packages. Pass --npm to use npm instead.

This message comes from an internal call of `expo prebuild`. Since `expo run:android` does not have an `--npm` option, running `expo run:android --npm` won't do anything.

---

The current workaround for this issue is to manually run the prebuild step of the `expo run:android` command, i.e.:

1. `expo prebuild --platform android --npm`
2. `expo run:android`

---

Either adding an `--npm` option to the `expo run:android` command or checking for a lockfile on the project root could fix this.
Please have a look at #4387 which uses the latter approach.
