### ISSUE TITLE
Add flag to disable web server

### ISSUE THREAD

**Issue by sjchmiela** [expo/expo-cli#439]
Not always do people with `app.json#platforms` including `web` want to develop their apps on all 3 platforms at the same time.

It could be beneficial to add some sort of `--disable-web` flag or something similar to be able to prevent Webpack from starting when running `expo start`.

**Comment by fson** [comment]
Instead of adding a flag, perhaps we can make it so that there’s no harm whatsoever from webpack running in the background even if you don’t currently need it? We would not compile for the web (or at least not surface any web specific errors) until a web page is requested from the dev server. This would be analogous to how Metro works for Android/iOS and only serves bundles when requested.

The experience of running `expo start` without ant flags should be as good as possible and when you want to switch platforms, you then don’t have to restart the server with different flags, only press `a`, `i` or `w` to open the app in that platform.

**Comment by sjchmiela** [comment]
Even better! 🎉
