### ISSUE TITLE
Drop Node 6.x support after April 30th 2019

### ISSUE THREAD

**Issue by fson** [expo/expo-cli#457]
Expo CLI supports [Current Release, Active LTS and Maintenance LTS versions of Node.js.](https://github.com/nodejs/Release#release-schedule)

Node 6.x is coming to end-of-life on 30th of April 2019. After this it will no longer be supported by Expo CLI. After April, we will continue to support Expo CLI running on following Node.js versions:
- Current Release (12.x, to be released in April)
- Active LTS (10.x "Dubnium")
- Maintenance LTS (8.x "Carbon")

**Comment by byCedric** [comment]
Yes, please! 😄 

I see that `opn@5.4.0` is used in the `expo-cli` package. Sindre actually renamed it now to `open`, because the original `open` package is deprecated:

> Note: The original open package was recently deprecated in favor of this package, and we got the name, so this package is now named open instead of opn. If you're upgrading from the original open package (open@0.0.5 or lower), keep in mind that the API is different.

If you want to update, you'll have to switch to `open@6.x.x`. Which has dropped support for Node 6 already, as [you can see here](https://github.com/sindresorhus/open/commit/5c525b5f4f2472e35ace19d6df746bb355b8060a).

**Comment by fson** [comment]
This was done in #643! We now support Node v8, v10 and v12.
