### ISSUE TITLE
Expo-cli not installing in Ubuntu 22.04 and not working with nodejs@18.13.0 

### ISSUE THREAD

**Issue by KartikDotDev** [expo/expo-cli#4622]
### Summary

expo-cli isn't working with nodejs@18.13.0 and needs updating. Please provide more info.

### Environment

npm install -g expo-cli
![image](https://user-images.githubusercontent.com/90651659/211629056-f727e468-5be4-4ca0-bc2f-6b5eaee059d5.png)

### Please specify your device/emulator/simulator platform, model and version

Ubuntu 22.04, Node JS 18.13.0

### Reproducible demo or steps to reproduce from a blank project

run "npm install -g expo-cli" with nodejs version 18.13.0 installed as default

**Comment by Tz-etta** [comment]
I also face this problem.

**Comment by Elasukou** [comment]
i just went through this, so i uninstalled expo with `winget uninstall expo-cli`, used the command `npm install uuid@latest` and also updated svgo, `chokidare graphqlcom npm install svgo@latest`, `npm install chokidar@latest ` and `npm install graphql@latest`, although that didn't seem to make any difference. I reinstalled the expo
and I used `npm audit fix --force` and then `npm audit fix`, I used the command `expo --version` and everything ok! it just said that it hasn't been tested yet for the latest version of Node.JS just below 17.0.0, but it's working.

**Comment by byCedric** [comment]
Hi all! The `expo-cli` has been deprecated for some time now. We've migrated towards the CLI shipped within `expo` ([versioned CLI](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421)).

If you still run into issues when using `npx expo` instead of the global CLI, please open a new issue on [github.com/expo/expo](https://github.com/expo/expo).

Hope this helps!
