### ISSUE TITLE
"Unable to find expo in this project - have you run yarn / npm install yet? " 

### ISSUE THREAD

**Issue by EzequielPrado** [expo/expo-cli#4623]
### Summary

When I try to open a project with npm start the error appears. "Unable to find expo in this project - have you run yarn / npm install yet? " 

### Environment

npm start

### Please specify your device/emulator/simulator platform, model and version

android

### Reproducible demo or steps to reproduce from a blank project

{
    "main": "node_modules/expo/AppEntry.js",
    "scripts": {
      "start": "expo start",
      "android": "expo start --android",
      "ios": "expo start --ios",
      "web": "expo start --web",
      "eject": "expo eject"
    },
    "dependencies": {
      "@ffprobe-installer/ffprobe": "^1.1.0",
      "@react-native-community/cameraroll": "^4.0.1",
      "@react-native-community/masked-view": "0.1.10",
      "@react-native-community/netinfo": "6.0.0",
      "@react-native-community/slider": "3.0.3",
      "@react-navigation/bottom-tabs": "^5.8.0",
      "@react-navigation/material-bottom-tabs": "^5.2.16",
      "@react-navigation/material-top-tabs": "^5.3.13",
      "@react-navigation/native": "^5.7.3",
      "@react-navigation/stack": "^5.9.0",
      "@skele/components": "^1.0.0-alpha.40",
      "babel-preset-expo": "^8.3.0",
      "expo": "~42.0.3",
      "expo-av": "~9.2.3",
      "expo-camera": "~11.2.2",
      "expo-cameraroll": "^1.1.0",
      "expo-checkbox": "^1.0.3",
      "expo-device": "~3.3.0",
      "expo-image-picker": "~10.2.2",
      "expo-linear-gradient": "~9.2.0",
      "expo-media-library": "~12.1.2",
      "expo-notifications": "~0.12.3",
      "expo-status-bar": "~1.0.4",
      "expo-updates": "~0.8.3",
      "expo-video-player": "^2.0.1",
      "expo-video-thumbnails": "~5.2.1",
      "firebase": "8.2.3",
      "get-video-duration": "^3.1.0",
      "queue": "^6.0.2",
      "react": "16.13.1",
      "react-dom": "16.13.1",
      "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
      "react-native-bottomsheet-reanimated": "0.0.22",
      "react-native-elements": "^3.0.0-alpha.1",
      "react-native-expo-cached-image": "^1.3.1",
      "react-native-fast-image": "^8.3.4",
      "react-native-gesture-handler": "~1.10.2",
      "react-native-interactable-reanimated": "0.0.8",
      "react-native-mentions": "^1.1.4",
      "react-native-optimized-flatlist": "^1.0.4",
      "react-native-paper": "^4.7.1",
      "react-native-parsed-text": "0.0.22",
      "react-native-reanimated": "~2.2.0",
      "react-native-restart": "0.0.20",
      "react-native-screens": "~3.4.0",
      "react-native-tab-view": "^2.15.2",
      "react-native-unimodules": " ~0.14.6",
      "react-native-vector-icons": "^7.1.0",
      "react-native-web": "~0.13.12",
      "react-redux": "^7.2.1",
      "react-uuid": "^1.0.2",
      "react-visibility-sensor": "^5.1.1",
      "reanimated-bottom-sheet": "^1.0.0-alpha.22",
      "redux": "^4.0.5",
      "redux-thunk": "^2.3.0",
      "sentry-expo": "^4.0.0"
    },
    "devDependencies": {
      "@babel/core": "~7.13.0",
      "babel-plugin-module-resolver": "^4.1.0"
    },
    "private": true
  }

**Comment by ClenildoCardoso** [comment]
Amigo, geralmente esse erro acontece quando você não entra corretamente no diretório do projeto pelo terminal, aí o expo não acha o projeto no diretório padrão para iniciar.

Faz o seguinte:
Executar cd "o nome do seu projeto" e depois digita o expo start.

**Comment by byCedric** [comment]
Hi there! It looks like your issue requires a minimal reproducible example, but it is invalid or absent. Please prepare such an example and share it in a new issue.

**The best way to get attention to your issue is to provide a clean and easy way for a developer to reproduce the issue on their own machine.** Please do not provide your entire project, or a project with more code than is necessary to reproduce the issue.

A side benefit of going through the process of narrowing down the minimal amount of code needed to reproduce the issue is that you may get lucky and discover that the bug is due to a mistake in your application code that you can quickly fix on your own.

### Resources

- ["How to create a Minimal, Reproducible Example"](https://stackoverflow.com/help/minimal-reproducible-example)
- ["How to narrow down the source of an error"](https://expo.fyi/manual-debugging)

### Common concerns

#### "I've only been able to reproduce it in private, proprietary code"

You may not have spent enough time narrowing down the root cause of the issue. Try out the techniques discussed in this [manual debugging guide](https://expo.fyi/manual-debugging) to learn how to isolate the problem from the rest of your codebase.

#### "I didn't have time to create one"

That's understandable, it can take some time to prepare. We ask that you hold off on filing an issue until you are able to fully complete the required fields in the issue template.

#### "You can reproduce it by yourself by creating a project and following these steps"

This is useful knowledge, but it's still valuable to have the resulting project that is produced from running the steps, where you have verified you can reproduce the issue.
