### ISSUE TITLE
How to remove dialog box whenever going to show downloaded file using expo file system?

### ISSUE THREAD

**Issue by ikart3689** [expo/expo-cli#4680]
### Summary

Using expo FIlesystem.downloadasync() library how to remove dialogue box of folder ? Every time it asks to create new folder but I don't want to create new folder I want downloaded file in devices particular folder like e.g. download folder of android/IOS devices.
My requirement is when I press on download button the json file will be moved to devices particular folder but things went opposite to me it asks every time that what folder you have to used to save this file.

### Environment

![expo-env-info](https://user-images.githubusercontent.com/98100057/230894926-5f35bf38-fd5d-480f-8d99-5aea39d227a2.PNG)

### Please specify your device/emulator/simulator platform, model and version

Android 11+ / iphone 11 

### Reproducible demo or steps to reproduce from a blank project

![downloadfromurl](https://user-images.githubusercontent.com/98100057/230894970-a89fc0f1-0590-45ce-9513-994c2d29a951.PNG)

**Comment by byCedric** [comment]
Hi @ikart3689! [`FileSystem.downloadAsync`](https://docs.expo.dev/versions/latest/sdk/filesystem/#filesystemdownloadasyncuri-fileuri-options) should not trigger a dialogue.

If you have a question or need help with certain things, please use [chat.expo.dev](https://chat.expo.dev) instead of opening a new issue. Issue reports are strictly used for (potential) issues.

Hope this helps!
