### ISSUE TITLE
Missing `withUnimodules`

### ISSUE THREAD

**Issue by axelekwall** [expo/expo-cli#4701]
### Summary

The recent update to the `@expo/webpack-config` package with the removal of the `withUnimodules` function has broken the expo storybook example implementation for the web. The function is still mentioned in the [README](https://github.com/expo/expo-cli/blob/main/packages/webpack-config/README.md) and in the `with-storybook` example [here](https://github.com/expo/examples/blob/471fb60e690fd4fd5fcf934cd9adbb635b0b5f4b/with-storybook/.storybook/webpack.config.js).

Related issue in `expo/examples` repo: https://github.com/expo/examples/issues/422

### Environment

N/A

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

```
ERR! TypeError: withUnimodules is not a function
ERR!     at module.exports (~/expo-examples/with-storybook/.storybook/webpack.config.js:5:10)
```

### Reproducible demo or steps to reproduce from a blank project

1. Follow the `with-storybook` expo example instructions for web.
2. Get error when trying to run the example.

**Comment by brandon-gs** [comment]
Any update here?

**Comment by jaronoff97** [comment]
also looking for updates 😭

**Comment by schlosser** [comment]
Also running into this!

**Comment by axelekwall** [comment]
Unfortunately I don't have any updates on this. We decided to not follow through with our Storybook setup and I haven't looked more into this since.

**Comment by EvanBacon** [comment]
`withUnimodules` was a bit of a misleading name since unimodules were a native feature and the function configured Webpack to load react-native-web + modules maintained by the Expo team. In many ways a better name would be `withMetroFeatures`. Regardless, it seemed that this was mostly used for Storybook and the Storybook team has a more official solution now. I've updated the example accordingly.
