### ISSUE TITLE
node_modules not found , even after npm install command

### ISSUE THREAD

**Issue by TheGlitchh** [expo/expo-cli#480]
## Description

Well I have installed expo-cli via `npm install -g expo-cli` it worked successfully  and then I did `expo init  myapp` it ran successfully  but when I ran `expo start` or `npm start` it connects to the local host but after a second or two it says node_modules not found , even I tried `npm install` but it gives bad system call 
How to solve it

**Comment by thg303** [comment]
please consider providing these information:

- Your PATH environment (output of `echo $PATH`),
- OS details (like Window/Linux or Mac including the version).
- The output of `expo diagnostics`.

**Comment by GalacticRogue** [comment]
Path environment : - `/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets`

OS details :- Termux on android 

Output of expo diagnostics  :- cannot read properly  `then` of undefined

**Comment by thg303** [comment]
before any thing, you have to install your node properly. your path should lead to npm and node binaries. please follow instructions for installing nodejs from their website or google about it.

btw, are you trying to develop your app on android os??? if you're interested in linux, why not trying ubuntu?

**Comment by GalacticRogue** [comment]
Well I have installed nodejs correctly , cause there is only one way to install it on termux I.e., `pkg install nodejs`  and I have seen people running expo-cli on termux rather spending money on buying a linux distro , so if you can help it out with it and If i haven't correctly installed nodejs then `npm install -g expo-cli` would not been installed correctly which in my case , it did without an issue.

**Comment by thg303** [comment]
if you insist on using android, I think you have to forget about using scripts part in the package.json file because Android does not have a PATH environment variable which is necessary to run scripts.
to start expo, find the binary in the `node_modules/bin` path of your node installation directory (maybe `$PREFIX/lib/node_modules/bin`) once you found it, you can run the bundler like this:
`node _PATH_TO_YOUR_EXPO_CLI_ start`

ps: most linux distributions are free just like android. including [Ubuntu](https://www.ubuntu.com/download/desktop), [Debian](https://www.debian.org/distrib/), [Fedora](https://getfedora.org/), etc.

**Comment by sergeichestakov** [comment]
Expo does not support Termux for Android. Most Linux distros are free.

If this is still an issue for you, please post the bad system call that is being thrown when you run `npm install`.

**Comment by jkhales** [comment]
Closing as this seems resolved.
