### ISSUE TITLE
Can somebody help me resolving this error? Facing it while deploying my react native app over AWS Amplify. Cannot find module 'expo/config'

### ISSUE THREAD

**Issue by ashutosh129520** [expo/expo-cli#4801]
### Summary

Can somebody help me resolving this error? Facing it while deploying my react native app over AWS Amplify. 

### Environment

NA

### Please specify your device/emulator/simulator platform, model and version

ios 

### Error output

Can somebody help me resolving this error? Facing it while deploying my react native app over AWS Amplify. 
2023-12-28T08:17:36.625Z [INFO]: # Executing command: expo build:web
2023-12-28T08:17:36.873Z [WARNING]: [08:17:36] Cannot find module 'expo/config'
                                    Require stack:
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/env/paths.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/env/validate.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/env/index.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/index.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack.config.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/xdl/build/Webpack.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/xdl/build/internal.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/xdl/build/index.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/build/exp.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/bin/expo.js
2023-12-28T08:17:36.884Z [WARNING]: [08:17:36] Error: Cannot find module 'expo/config'
                                    Require stack:
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/env/paths.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/env/validate.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/env/index.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/index.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack.config.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/xdl/build/Webpack.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/xdl/build/internal.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/xdl/build/index.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/build/exp.js
                                    - /root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/bin/expo.js
                                    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
                                    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
                                    at Module.require (internal/modules/cjs/loader.js:974:19)
                                    at require (internal/modules/cjs/helpers.js:101:18)
                                    at Object.<anonymous> (/root/.nvm/versions/node/v14.21.2/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/src/env/paths.ts:2:1)
                                    at Module._compile (internal/modules/cjs/loader.js:1085:14)
                                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
                                    at Module.load (internal/modules/cjs/loader.js:950:32)
                                    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
                                    at Module.require (internal/modules/cjs/loader.js:974:19)
2023-12-28T08:17:36.889Z [ERROR]: !!! Build failed
2023-12-28T08:17:36.890Z [ERROR]: !!! Non-Zero Exit Code detected

### Reproducible demo or steps to reproduce from a blank project

NA

**Comment by byCedric** [comment]
Hi there! It looks like your issue requires a minimal reproducible example, but it is invalid or absent. Please prepare such an example and share it in a new issue.

**The best way to get attention to your issue is to provide a clean and easy way for a developer to reproduce the issue on their own machine.** Please do not provide your entire project, or a project with more code than is necessary to reproduce the issue.

A side benefit of going through the process of narrowing down the minimal amount of code needed to reproduce the issue is that you may get lucky and discover that the bug is due to a mistake in your application code that you can quickly fix on your own.

### Resources

- ["How to create a Minimal, Reproducible Example"](https://stackoverflow.com/help/minimal-reproducible-example)
- ["How to narrow down the source of an error"](https://expo.fyi/manual-debugging)

### Common concerns

#### "I've only been able to reproduce it in private, proprietary code"

You may not have spent enough time narrowing down the root cause of the issue. Try out the techniques discussed in this [manual debugging guide](https://expo.fyi/manual-debugging) to learn how to isolate the problem from the rest of your codebase.

#### "I didn't have time to create one"

That's understandable, it can take some time to prepare. We ask that you hold off on filing an issue until you are able to fully complete the required fields in the issue template.

#### "You can reproduce it by yourself by creating a project and following these steps"

This is useful knowledge, but it's still valuable to have the resulting project that is produced from running the steps, where you have verified you can reproduce the issue.
