### ISSUE TITLE
[sdk33] Fix progress bar with SDK 33

### ISSUE THREAD

**Issue by ide** [expo/expo-cli#543]
React Native CLI or Metro broke the progress bar again; need to fix it.

**Comment by fson** [comment]
The problem was that the `--customLogReporterPath` option was not working in the latest React Native CLI. This probably broke when the CLI switched to use the new config format of `metro-config`.

I've fixed the React Native CLI bug here: https://github.com/react-native-community/cli/pull/370. Should we wait for a CLI release or patch the CLI in SDK 33 branch somehow?

**Comment by ide** [comment]
> patch the CLI in SDK 33 branch somehow

This is messy and it's easier to backport the fix to an older RN CLI version. I'll talk to Brent about that today.

**Comment by fson** [comment]
I've cherry-picked the fix to the RN CLI 1.x branch here: https://github.com/react-native-community/cli/pull/371

**Comment by ide** [comment]
Closing since RN CLI published this in 1.9.3.
