### ISSUE TITLE
[web] Ability to overwrite default css?

### ISSUE THREAD

**Issue by ericyip** [expo/expo-cli#660]
Default css apply `flex: 1` to all direct div inside body. It affects to `createPortal` or FBSDK which default insert div inside body.

https://github.com/expo/expo-cli/blob/4405ec1094942a8d03f3d0f1a886a2768e688436/packages/webpack-config/web-default/index.html#L24-L30

My currently workaround is 
```js
   // cDM
    if (Platform.OS === 'web' && document) {
      const rnwStyleSheet = document.getElementById('react-native-stylesheet')
      if (rnwStyleSheet) {
        rnwStyleSheet.sheet.insertRule(`#fb-root { display: none;}`, 0);
        rnwStyleSheet.sheet.insertRule(`body > div { flex: 0;}`, 0);
        rnwStyleSheet.sheet.insertRule(`#root { flex: 1;}`, 0);
      }
    }
```

Is there any better way to do?

**Comment by fson** [comment]
@EvanBacon maybe we could make the default styles less intrusive by instead of targeting `body > div`, adding a `class` to the root div and targeting that with the selector, or targeting `#%ROOT_ID`?

**Comment by EvanBacon** [comment]
Until the fix is merged you should create the file `web/index.html` and copy over the [default file contents](https://github.com/expo/expo-cli/blob/master/packages/webpack-config/web-default/index.html). Then the CLI will automatically use that file instead of the default. There is another PR open to add a command that will auto generate this file #684.

**Comment by EvanBacon** [comment]
I'm also going to work on a better flow for debugging prod mode. You can currently do this by running `expo start --no-dev` but the bundle is minified so we need a way to enable debug prod mode.
