### ISSUE TITLE
extracting very slow when using expo init

### ISSUE THREAD

**Issue by buzzhoot** [expo/expo-cli#72]
it takes up to 5 minutes to extracting when using expo init
i am running win10 on 5960x

**Comment by ameybhavsar24** [comment]
I am facing the same issue. Any updates?

**Comment by fson** [comment]
After this issue was opened in 2018, we have completely changed how `expo init` downloads and extracts templates. The templates are now downloaded from npm and they no longer include bundled dependencies and the dependencies are installed with npm/Yarn instead.

This should make things faster, as many of the packages can already be cached by npm/Yarn and there's no extracting huge 100MB+ template packages anymore.
