### ISSUE TITLE
expo and expo-cli are not recognised as commands

### ISSUE THREAD

**Issue by v-beletskiy** [expo/expo-cli#727]
The fix has been released in the version `31.0.6` of the `expo` package. The workaround described above is no longer necessary when using `expo@31.0.6` or later.

_Originally posted by @fson in https://github.com/expo/expo-cli/issues/51#issuecomment-444108426_

Solutions, mentioned here https://github.com/expo/expo-cli/issues/51 don't work.

See the same problem - expo and expo-cli are not recognised as commands.
Can't start the project neither by npm run start, nor explicitly by expo start. expo-cli start doesn't work as well. It is proposed to install expo-cli in cmd, but after installation ... it is proposed to install expo-cli.

Tried different versions of expo. Use "expo": "^33.0.5" for now.

**Comment by v-beletskiy** [comment]
Any ideas? Expo-cli is being installed successfully, but running expo commands afterwards leads to the notification that expo command is not found. Please, help.

**Comment by Exoshale** [comment]
Are you on Windows? Mac? 

I would verify that your PATH environment variable contains a reference to NPM prefix. I had a similar issue on Mac where it was being set in Terminal, but VS Code had the wrong prefix.

**Comment by v-beletskiy** [comment]
Windows 10.
I've got this one. 
![image](https://user-images.githubusercontent.com/35741786/59876578-a7c6ea80-93ac-11e9-84bd-08d830951880.png)

**Comment by kareniukas** [comment]
How you fix this on mac?

**Comment by eddskt** [comment]
i have the same problem, but in macOS, expo and expo-cli installed, PATH ok, but, on bash expo command is not recognized

**Comment by jerlam06** [comment]
Same issue

**Comment by EvanBacon** [comment]
To get the expo-cli `expo` command, run `npm i -g expo-cli`. Any issue outside of that is out of scope for this repo and most likely due to how node is installed on a computer. The issue can also occur when expo-cli is installed with `sudo` (never do this please).

Closing this issue because it's pretty old, so visibility won't be great for users looking to find a quick troubleshooting tip. I highly recommend using Stack Overflow, or the Expo forums for more active/better support.
