### ISSUE TITLE
Not Finish Install expo-cli without error, 2 hours not finish 

### ISSUE THREAD

**Issue by deviapriliaas** [expo/expo-cli#835]
npm WARN deprecated joi@14.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
npm WARN deprecated package has been deprecated in favor of directly
npm WARN deprecated including core-js/stable (to polyfill ECMAScript
npm WARN deprecated features) and regenerator-runtime/runtime
npm WARN deprecated (needed to use transpiled generator functions):
npm WARN deprecated
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
[            ......] | extract:@expo/traveling-fastlane-darwin: sill extract @expo/traveling-fastlane-darwin@1.9.9 extracted to C:\Users\devia\AppData\Roaming\npm\node

**Comment by YoshiYo** [comment]
What is your version on node js ?

**Comment by deviapriliaas** [comment]
> What is your version of nodejs ?

my nodejs version is 12.6.0

**Comment by zhoujunboo** [comment]
同问题，我的node版本10.16.0，通过nvm安装的node

**Comment by Ismail-Opatola** [comment]
I'm having the same issue, any idea on how to fix it? i'm running node v12.0.0

**Comment by GuilhermeEsdras** [comment]
I'm having the same issue. 
Node version: v10.16.0

**Comment by Ismail-Opatola** [comment]
This stuff just keeps hanging.

`
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> npm install -g expo-cli
[ .................] | fetchMetadata: sill resolveWithNewModule isexe@2.0.0 checking installabnpm WARN deprecated joi@14.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
[` .......npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
npm WARN deprecated package has been deprecated in favor of directly
npm WARN deprecated including core-js/stable (to polyfill ECMAScript
npm WARN deprecated features) and regenerator-runtime/runtime
npm WARN deprecated (needed to use transpiled generator functions):
npm WARN deprecated
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN tarball tarball data for @expo/ngrok-bin-win32-ia32@2.2.8-beta.1 (sha512-Pva9ZNjUieD2/RVav7LYGAXZ1O6MVXlvOnJmHSmjP4rhreek7/Ez7b5HsCEN3YLjZIcPHH8SV8Duix1NO2zB5A==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @expo/traveling-fastlane-darwin@1.9.9 (sha512-rz6gSbRrJI/g+JNgSunAX//TpedIpEGhLnB6H5uTtGl3Oqg/UkLIDlCjtHCdPrHAVRQqCR1qdT9k3AXbEYFV1w==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @expo/traveling-fastlane-linux@1.9.9 (sha512-DKfeDhfeXmYhfM/CT7yiPjyvEMFyLvEDuKU3RIdieMZ3CJOobTkdaOQlQd39VYZ+q1a1qL5QvTiIlPvcSXv9PQ==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @expo/ngrok-bin-linux-x64@2.2.8 (sha512-jNhnnfMR/yAgUV1LnAheq/WWB/Tkdgm5sxZhN0fjN00CeiYTVyNuCsii2tdjXJCGrxdpb6RzvOxjLGstIT0mUQ==) seems to be corrupted. Trying one more time.
[ ......] / extract:rxjs: WARN tarball tarball data for @expo/ngrok-bin-linux-x64@2.2.8 (sha512-jNhnnfMR/yAgUV1Ln
`

I've tried `npm cache verify` and also clearing the cache but the error still persist. This issue seems to be happening to 64bit operating systems

**Comment by voronindenis** [comment]
I'm having the same issue.
Node version: v10.16.0

**Comment by smachar** [comment]
same here 
Node version: v10.16.0

**Comment by deviapriliaas** [comment]
I delete all directory from node and npm, at local data too, and then tried to installl again from nodejs website, after than everything can running again
