### ISSUE TITLE
Could not get status from Metro bundler

### ISSUE THREAD

**Issue by raghuram15** [expo/expo-cli#949]
Hi ,

I am getting the below issue when i try to run the app not able to solve 

**Could not get status from Metro bundler. connect ECONNREFUSED 127.0.0.1:19001
Connecting to Metro bundler failed.**

**Comment by oegonzal** [comment]
I am also getting this issue and update on this issue?

**Comment by oegonzal** [comment]
Restarting my computer fixed this for me!

**Comment by cruzach** [comment]
This can usually happen when publishing without ever having run `expo start`, also it's a good idea to run `rm -rf .expo` to clear your local state

We can probably do a better job with this and intercept the error message to provide better feedback

**Comment by cruzach** [comment]
Closing this since it's listed in our [common development errors](https://docs.expo.io/versions/latest/workflow/common-development-errors/#metro-bundler-econnrefused-12700119001) and will try to get a repro via participants in [580](https://github.com/expo/expo-cli/issues/580) so we can improve the error message
