### ISSUE TITLE
expo android command fails to start an Expo application

### ISSUE THREAD

**Issue by SounD120** [expo/expo-cli#951]
## Description

Fresh Expo app generated with `tabs` template doesn't work if it has being ran with `expo android` command. 

## Expected Behavior

Fresh generated Expo app with `tabs` template runs with command `expo android` successfully without errors.

## Observed Behavior

The following error message shows up on tested device and emulator: 
![image](https://user-images.githubusercontent.com/32372875/63435470-9f803f80-c42f-11e9-883a-0397c7abe877.png)

After investigation I found out that the following message is returned from my Expo server:
`{"error":"XDLError: ValidationError: \"https\" is not allowed"}`

Then I opened `myExpoProject/.expo/settings.json` file and found the following line:
```
 "https": false
```
It looks like standard Expo execution settings are blocking `https`, but https is still used in the sample application.

Full `settings.json`:
```
{
  "hostType": "lan",
  "lanType": "ip",
  "dev": true,
  "minify": false,
  "urlRandomness": null,
  "https": false
}
```
## Environment

```
  Expo CLI 3.0.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.17.3 - C:\Users\yuri.skorokhodov\AppData\Roaming\npm\yarn.CMD
      npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
```
Tested on:
Acer liquid zest t06 Android 6.0
Android Studio emulator x86 API 28 Android 9.0

## Reproducible Demo

* Create template Expo app with the following command: 
`expo init -t tabs --name expo_app  expo_app`
* `cd expo_app`
* `expo android`

**Comment by bfreis** [comment]
I'm having the same issue. Until ~yesterday everything was working fine, today it doesn't work anymore. I get the same blue screen on my Android devices (both my main Pixel 3, and a Pixel 1 that I just did a factory reset).

Also, could be related, my terminal on my computer shows the following:

```
Couldn't adb reverse: adb: error: Invalid source port: 'null'
Opening on Android device
This version of the Expo app is out of date. Uninstall the app and run again to upgrade.
```

I checked on the Play Store and the Expo client is up to date.

I also tried to uninstall the Expo client and let the `expo android` command install it, but it gives me the same error.

Also, if I open `View error log` on the Android, it shows a ConnectExpection being thrown. For some reason, it's trying to connect to `192.168.x.x:80`. The IP address is my computer's IP address, so that looks correct. However, the port number, 80, looks suspicious — it should probably be something else. Seems like the port is not being properly sent to my devices.

**Comment by bfreis** [comment]
Oh, I also meant to say that it seems like the Expo client is almost completely broken.

On my Pixel 3, on which I've had the Expo client installed for a while, I can open the client and it correctly shows my projects, profile, etc.

However, on my Pixel 1 — that I just did a factory reset like an hour ago — the Expo client doesn't work at all. It shows the a black Expo logo on a white background, and hangs there forever. I tried to force stop, clean cache, clean storage, remove and install again from the Play Store, remove and let the `expo android` command install it, the result is always the same.

Not sure, but it might be related.

**Comment by superandrew** [comment]
I have noticed an identical problem on iOs as well. After many tries I was able to make the app run again, and I noticed the `"https":false` line was gone from `.expo/settings.json`.

That was very difficult and frustrating to discover.

**Comment by EvanBacon** [comment]
`expo android` command has been removed in favor of `expo start --android`. It's purpose afaict was to open an already running instance of the Metro dev server. The error may have been due to `expo android` not actually starting the server correctly.
