### ISSUE TITLE
expo upload:ios stuck in CI

### ISSUE THREAD

**Issue by alialaa** [expo/expo-cli#954]
Hello, I was trying to run `expo upload:ios` on travis however at some point I get a two factor authentication code on my phone while the message is not actually asking for any code (I know I cannot put input in CI anyways). It's stuck at "Ensuring the app exists on App Store Connect, this may take a while..."

Is there a way to upload on CI?

**Comment by alexandermckay** [comment]
This may help you:

[11:13:47]: [Transporter Error Output]: Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)
[11:13:47]: Transporter transfer failed.
[11:13:47]: 
[11:13:47]: Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)
[11:13:48]: 
[11:13:48]: Your account has 2 step verification enabled
[11:13:48]: Please go to https://appleid.apple.com/account/manage
[11:13:48]: and generate an application specific password for
[11:13:48]: the iTunes Transporter, which is used to upload builds
[11:13:48]: 
[11:13:48]: To set the application specific password on a CI machine using
[11:13:48]: an environment variable, you can set the
[11:13:48]: FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD variable

**Comment by MoonTahoe** [comment]
I'm having the same issue running `expo upload:ios` from Github Actions. The command works fine for me locally, but I can't get it to work in actions.

## Two Factor Auth Issue

The problem is that if I use my `apple-id` and `apple-id-password` that are associated with my Apple account, I run into 2FA issues:

```yaml
- name: Deploy to Testflight
  run: expo upload:ios --apple-id $EXPO_APPLE_ID --apple-id-password $EXPO_APPLE_PASSWORD
  env:
    EXPO_APPLE_ID: ${{secrets.EXPO_APPLE_ID}}
    EXPO_APPLE_PASSWORD: ${{secrets.EXPO_APPLE_ID_PASSWORD}}
```

Using my username and password, the app store recognizes me, but it then sends me a code on my phone that I am supposed to enter via stdin. I can't do that with Github actions. This is the resulting output:

```
[00:29:50] Resolving the ITC team ID...
Two-factor Authentication (6 digits code) is enabled for account '***'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship_2fa_sms_default_phone_number)

Please enter the 6 digit code:
[00:29:53] Failed to upload the standalone app to the app store.
[00:29:53] The input stream is exhausted.
```

## App Specific Password

So the solution for CI is to use an app specific password. I created an app specific password, and just to be sure everything is was working ok I ran `expo upload:ios --apple-id 🤫 --apple-id-password 🤫` locally on my mac and it worked, it uploaded my last build to TestFlight. (Assume the 🤫 are the correct id and password). I hard coded them into the command just to be sure.

So, for some reason, when I run the exact same command with the exact same App Specific Password in Github, I get an error saying invalid apple id credentials:

```yaml
run: expo upload:ios --apple-id 🤫 --apple-id-password 🤫
```

This is what the output on Github Actions looks like:

```
Run expo upload:ios --apple-id 🤫 --apple-id-password 🤫
[20:15:57] Accessing credentials for *** in project MacCheese
[20:15:59] Downloading build from https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/%40***/MacCheese-cc930f79-18ac-4e33-937d-771613bcd004-archive.ipa

[20:16:03] Resolving the ITC team ID...
[20:16:07] Failed to upload the standalone app to the app store.
[20:16:07] Invalid Apple ID credentials
[20:16:07] Error: Invalid Apple ID credentials
```

The reason that I hardcoded the `apple-id` and `apple-id-password` into the command, is because I've tried everything. I've tried every combination of environment variable under the sun. I read some stuff on App specific passwords in the error message, so I tried adding more environment variables to make that work too:

```yaml
- name: Deploy to Testflight
  run: expo upload:ios --apple-id $EXPO_APPLE_ID --apple-id-password $EXPO_APPLE_PASSWORD
  env:
    EXPO_APPLE_ID: ${{secrets.EXPO_APPLE_ID}}
    EXPO_APPLE_PASSWORD: ${{secrets.EXPO_APPLE_ID_PASSWORD}}
    FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_PASSWORD }}
    APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_PASSWORD }}
```

I know I have the correct ID, password, and App Specific password because I updated them a billion times. For some reason the `expo upload:ios` command with an app specific password will work locally, but not on Github actions. 

Any suggestions?

**Comment by eladtaranis** [comment]
Any update on this one?

**Comment by brentvatne** [comment]
`expo upload:ios` has been replaced by `eas submit` as described here https://github.com/expo/expo-cli/issues/2192#issuecomment-745626708
